import type { ComponentMeta } from "@/lib/types";
export default {
  title: "分页 Pagination", titleEn: "Pagination", description: "页位置、真实入口与明确的未知总数。", descriptionEn: "Page position, real actions and explicit unknown totals.",
  category: "导航", layer: "pattern", source: "local", exports: ["Pagination", "PaginationList", "PaginationItem", "PaginationLink", "PaginationPrevious", "PaginationNext", "PaginationEllipsis"],
  decisions: "只从 root page 与 link page 相等推导当前位置。总页数 null 表示未知；不创建末页或推断下一页存在。", decisionsEn: "Only current position is derived by comparing root and link page facts. null means an unknown total; no final page or next-page availability is inferred.",
  design: { methods: ["名实相符", "展开有据"], whenToUse: ["结果按页呈现，页位置和方向可用性已知。"], avoid: ["过程进度用 Steps；不确定结果总数时不伪造末页。"], stateOwner: { library: ["页入口的导航、列表、当前页语义与真实禁用。"], application: ["页内容、当前页、总数或未知、前后页可用性与请求结果。"] }, responsive: ["动作可换行，保留当前页与总数状态。"] }, designEn: {"whenToUse":["Results are paged and positions/navigation availability are known."],"avoid":["Use Steps for process progression; never invent a last page when totals are unknown."],"stateOwner":{"library":["Navigation, lists, current-page semantics, and actual disabling of page entries."],"application":["Page content, current page, known/unknown totals, previous/next availability, and request outcomes."]},"responsive":["Actions wrap while retaining current-page and total states."]},
  keywords: ["pager", "pages", "分页", "翻页", "页码"],
  api: [
    { name: "Pagination", description: "有名称的 nav，不生成页码。", descriptionEn: "A named nav without generated pages.", props: [{ name: "page", type: "number", description: "应用确认的当前正整数页码，零结果可省略。", descriptionEn: "A confirmed positive page index; omit for zero results." }, { name: "totalPages", type: "number | null", description: "必填非负整数总页数或 null=未知；在内容中明确未知状态。", descriptionEn: "Required nonnegative total or null for unknown; explain unknown state visibly." }, { name: "aria-label / render / ref / native props", type: "useRender.ComponentProps<nav>", description: "默认名称来自 locale。", descriptionEn: "The default name is localized." }] },
    { name: "PaginationList / PaginationItem", description: "ul / li 组织页面入口。", descriptionEn: "ul / li organize page actions.", props: [{ name: "render / ref / native props", type: "useRender.ComponentProps<ul | li>", description: "保留原生列表结构。", descriptionEn: "Preserve native list structure." }] },
    { name: "PaginationLink", description: "a，匹配当前页时 aria-current=page。", descriptionEn: "An anchor with aria-current=page for the current page.", props: [{ name: "page / href / render / ref / native props", type: "{ page: number } & useRender.ComponentProps<a>", description: "应用提供正整数页码与真实目标。", descriptionEn: "The application supplies positive page indices and real destinations." }] },
    { name: "PaginationPrevious / PaginationNext", description: "复用 Button 与本地化方向名称。", descriptionEn: "Button compositions with localized direction labels.", props: [{ name: "disabled / onClick / render / nativeButton / Button props", type: "ButtonProps", description: "应用明确禁用；导航可 render 为 a 并设 nativeButton=false。", descriptionEn: "The caller supplies disabled facts; render an anchor with nativeButton=false for navigation." }] },
    { name: "PaginationEllipsis", description: "省略页名称，不代表末页。", descriptionEn: "An omitted-pages marker, not a final page.", props: [{ name: "children / render / native props", type: "useRender.ComponentProps<span>", description: "仅在已知有省略页时提供。", descriptionEn: "Use only when omitted pages are known to exist." }] },
  ], notes: ["不请求数据、保存路由或自动截取页码；未知总数不证明有无下一页。"], notesEn: ["No fetching, routing or automatic page window; unknown totals establish no next-page availability."],
} satisfies ComponentMeta;
