import type { ComponentMeta } from "@/lib/types";
export default {
  title: "图表 Chart", titleEn: "Chart", description: "七种由任务选定的形式——折线、柱状、面积、堆叠面积、横向柱、堆叠柱、环形；同源的图形、命名的轴与按需展开的数据表。", descriptionEn: "Seven task-chosen forms—line, bar, area, area-stacked, bar-horizontal, bar-stacked and donut—with a same-source plot, named axes and an on-demand data table.", category: "数据展示", layer: "pattern", source: "local", exports: ["Chart"], keywords: ["chart", "line chart", "bar chart", "area chart", "donut chart", "图表", "折线", "柱状", "面积", "环形", "堆叠", "趋势", "比较", "构成", "占比", "等价表格"],
  decisions: "已知0、无记录、未知和不适用分别成立；未知值形成gap，表格保留其真实名称。图形不替代可达数值。", decisionsEn: "Known zero, empty data, unknown and not-applicable values remain distinct. Unavailable values form gaps and retain their actual names in the table. Plots do not replace reachable numbers.",
  api: [{ name: "Chart", description: "figure名称、共同轴量纲、不同系列形态与同源可见Table。", descriptionEn: "A named figure, shared axis units, distinct series shapes and a visible same-source Table.", props: [
    { name: "label", type: "string", description: "非空真实语义名称。", descriptionEn: "A nonempty semantic name for the actual data." },
    { name: "state", type: '"ready" | "empty" | "unknown" | "not-applicable"', default: '"ready"', description: "真实整图事实；非ready由children表达，不造数字或坐标轴。", descriptionEn: "The actual chart-wide state. children describe non-data states without invented numbers or axes." },
    { name: "type", type: '"line" | "bar" | "area" | "area-stacked" | "bar-horizontal" | "bar-stacked" | "donut"', description: "由任务选定的形式，不是外观偏好：line 随时间/次序的趋势；bar 类别间比较；area 随时间的量（单系列第一色淡面，多系列默认半透叠放）；area-stacked 随时间的构成（淡色带加足色上沿，彼此相切）；bar-horizontal 类别名长或按大小排序的排行；bar-stacked 类别间的构成比较；donut 只用于 2–5 个部分、一眼占比的单个整体（rows 必须正好一行）。必填。", descriptionEn: "The form chosen by the task, not an appearance preference: line for trends over time/order; bar for category comparison; area for a quantity over time (a first-color wash for one series, translucent overlap by default for several); area-stacked for composition over time (opaque light bands with full-color top edges, touching); bar-horizontal for long category names or size-ordered rankings; bar-stacked for composition comparison between categories; donut only for an at-a-glance share of 2–5 parts in a single whole (rows must be exactly one). Required." },
    { name: "categoryLabel / valueLabel", type: "string", description: "非空分类轴名与共享量纲/单位；donut 不画轴线，但两个名字仍用于等价数据表与中心读数的说明文字。", descriptionEn: "Nonempty category axis name and shared value units; donut draws no axis lines, but both names still label the equivalent table and the center readout." },
    { name: "series", type: "readonly { key: string; label: string }[]", description: "1至5个同量纲系列（donut 要求2至5个）。只有一个系列时取第一色（文字是墨，数据是色）、不显示图例；两个以上按 chart1..5 的校验顺序取色，并配不同标记形状或图例方块。", descriptionEn: "One to five series in shared units (donut requires two to five). A single series takes the first color (text is ink, data is color) without a legend; two or more take the validated chart1..5 order with distinct marker shapes or legend swatches." },
    { name: "rows", type: "readonly ChartRow[]", description: "稳定id、分类名称与values；值为finite number或{state:unknown|not-applicable,label}。ready必须有真实记录；donut 要求正好一行，且每个部分必须是已知的非负数。", descriptionEn: "Stable ids, category names and values: finite numbers or explicitly named unknown/not-applicable values. ready requires actual records; donut requires exactly one row, with every part a known non-negative number." },
    { name: "total", type: "number", description: "只用于 donut：整体的总量。省略时等于各部分之和；大于之和时，剩余部分并入「其余」（groove-surface，不是第六种色相）。", descriptionEn: "Donut only: the whole's total. Defaults to the sum of its parts; a larger value folds the remainder into a neutral \"rest\" slice (groove-surface, not a sixth hue)." },
    { name: "formatValue", type: "(value, series, row) => ReactNode", description: "格式化已知数值；默认按UILocale数值Intl，不改数据。", descriptionEn: "Format known values without changing data. Defaults to Intl number formatting for UILocale." },
    { name: "renderPlot", type: "(projection: ChartPlotData) => ReactNode", description: "替换同源图形；gap为null，默认LineChart不连接gap且不动画。名称、图例与可见Table始终保留。自定义图形承担自身交互/ARIA。", descriptionEn: "Replace the same-source plot. Gaps project to null; the default LineChart neither connects gaps nor animates. Names, legend and visible Table remain. Custom plots own their interaction and ARIA." },
    { name: "style / className / render / ref", type: "ChartStyle / useRender组合", typeEn: "ChartStyle / useRender composition", description: "根style可覆写 --qy-chart-plot-height（默认 10 材）。线宽、标记与柱宽是图的法度，不开放逐个配置。", descriptionEn: "Root style may override --qy-chart-plot-height (default 10 modules). Line width, markers and bar width are fixed by the chart's rules rather than configured individually." },
  ] }], notes: ["null、NaN、Infinity、缺失键不能表示0；用显式unknown或not-applicable表达。", "所有值均未知时不画虚假数值轴，名称、图例与表格保留。", "默认图形为数据表的视觉补充，辅助技术使用展开后的数据表；悬停读数只增强，不替代数据表。", "长名称在可见Table保留，图形轴的公共碰撞处理不表示记录丢失。", "浅深必要图形对真实背景至少3:1、文字至少4.5:1，由浏览器owner核实。", "donut 超过5个部分或需要精确比较时改用 Proportion 或 bar/bar-horizontal；两个量的关系用 ScatterChart，两个类别维度上的量用 Heatmap——它们数据形状不同，是独立组件而不是 Chart 的 type。"],
  notesEn: ["null, NaN, Infinity and missing keys cannot stand for zero. Use explicit unknown or not-applicable values.", "When every value is unavailable, no fabricated numeric axis is drawn; names, legend and table remain.", "The default plot supplements the data table, which provides assistive access once expanded; hover readouts enhance but never replace it.", "The visible Table retains full names. Axis collision handling does not mean records are missing.", "The browser owner verifies light/dark contrast: necessary graphics at least 3:1 against the actual background and text at least 4.5:1.", "Past five donut parts, or when precise comparison matters, use Proportion or bar/bar-horizontal instead. The relationship between two quantities is ScatterChart; a quantity over two categorical dimensions is Heatmap — both have a different data shape and are separate components, not a Chart type."],
  designEn: { whenToUse: ["Real values in shared units need graphical comparison with reachable numeric equivalents."], avoid: ["Mixed units, guessed results, connecting unavailable values as a reliable trend, or relying on color alone.", "A donut with more than five parts, or where share must be compared precisely rather than glanced at."], composition: ["Public Recharts primitives with current Table and Empty; one rows/series projection."], stateOwner: { library: ["Same-source projection, visible equivalent table, series shapes and basic naming."], application: ["Data, units, truth, state content and custom plotting."] }, responsive: ["A centralized 12em plot height can be overridden. The table scrolls and wraps without cutting actual values."], customization: ["Existing chart1..5 semantic colors, local plot roles and public renderPlot; no separate chart palette."] },
  design: { methods: ["名实相符", "相成相制", "布白有用"], whenToUse: ["真实共享量纲数据需要图形比较，且等价值可达。"], avoid: ["混合量纲、猜测结果、把缺值连成可靠趋势或仅靠颜色。", "环形超过5个部分，或占比需要精确比较而不是一眼大小。"], composition: ["Recharts公开原语 + 当前Table/Empty；同一rows/series投影。"], stateOwner: { library: ["同源投影、可见等价表、系列形态和基础名称。"], application: ["数据、量纲、真实性、状态文字与自定义图形。"] }, responsive: ["图高集中12em可覆写，表格原生滚动/换行；不裁掉实际值。"], customization: ["chart1..5语义角色；局部plot roles与公开renderPlot，不另造图表调色板。"] },
} satisfies ComponentMeta;
