import type { ComponentMeta } from "@/lib/types";
export default {
  title: "真实数值 Chart", titleEn: "Chart", description: "以同源图形、轴、图例和可见数值表呈现真实数据。", descriptionEn: "Present real data with a same-source plot, axes, legend and visible numeric table.", category: "数据展示", layer: "pattern", source: "local", exports: ["Chart"], keywords: ["chart", "line chart", "图表", "数值", "等价表格"],
  decisions: "已知0、无记录、未知和不适用分别成立；未知值形成gap，表格保留其真实名称。图形不替代可达数值。", decisionsEn: "Known zero, empty data, unknown and not-applicable values remain distinct. Unavailable values form gaps and retain their actual names in the table. Plots do not replace reachable numbers.",
  api: [{ name: "Chart", description: "figure名称、共同轴量纲、不同系列形态与同源可见Table。", descriptionEn: "A named figure, shared axis units, distinct series shapes and a visible same-source Table.", props: [
    { name: "label", type: "string", description: "非空真实语义名称。", descriptionEn: "A nonempty semantic name for the actual data." },
    { name: "state", type: '"ready" | "empty" | "unknown" | "not-applicable"', default: '"ready"', description: "真实整图事实；非ready由children表达，不造数字或坐标轴。", descriptionEn: "The actual chart-wide state. children describe non-data states without invented numbers or axes." },
    { name: "categoryLabel / valueLabel", type: "string", description: "非空分类轴名与共享量纲/单位。", descriptionEn: "Nonempty category axis name and shared value units." },
    { name: "series", type: "readonly { key: string; label: string }[]", description: "1至5个有唯一key与名称的同量纲系列，消费现有chart1..5及可区分marker/line。", descriptionEn: "One to five named series with unique keys and shared units, using existing chart1..5 colors and distinct markers/lines." },
    { name: "rows", type: "readonly ChartRow[]", description: "稳定id、分类名称与values；值为finite number或{state:unknown|not-applicable,label}。ready必须有真实记录。", descriptionEn: "Stable ids, category names and values: finite numbers or explicitly named unknown/not-applicable values. ready requires actual records." },
    { name: "formatValue", type: "(value, series, row) => ReactNode", description: "格式化已知数值；默认按UILocale数值Intl，不改数据。", descriptionEn: "Format known values without changing data. Defaults to Intl number formatting for UILocale." },
    { name: "renderPlot", type: "(projection: ChartPlotData) => ReactNode", description: "替换同源图形；gap为null，默认LineChart不连接gap且不动画。名称、图例与可见Table始终保留。自定义图形承担自身交互/ARIA。", descriptionEn: "Replace the same-source plot. Gaps project to null; the default LineChart neither connects gaps nor animates. Names, legend and visible Table remain. Custom plots own their interaction and ARIA." },
    { name: "style / className / render / ref", type: "ChartStyle / useRender组合", typeEn: "ChartStyle / useRender composition", description: "根style覆写局部plot-height/stroke-width/marker-size角色；默认12em/2px/8px为集中预设，实际图形和图例消费。", descriptionEn: "Root style overrides local plot-height/stroke-width/marker-size roles. Defaults of 12em/2px/8px are centralized presets consumed by the plot and legend." },
  ] }], notes: ["null、NaN、Infinity、缺失键不能表示0；用显式unknown或not-applicable表达。", "所有值均未知时不画虚假数值轴，名称、图例与表格保留。", "默认图形为数值表的视觉补充，辅助技术使用可见表；自定义renderPlot不被强制aria-hidden。", "长名称在可见Table保留，图形轴的公共碰撞处理不表示记录丢失。", "浅深必要图形对真实背景至少3:1、文字至少4.5:1，由浏览器owner核实。"],
  notesEn: ["null, NaN, Infinity and missing keys cannot stand for zero. Use explicit unknown or not-applicable values.", "When every value is unavailable, no fabricated numeric axis is drawn; names, legend and table remain.", "The default plot supplements the visible numeric table, which provides assistive access. Custom renderPlot content is not forced aria-hidden.", "The visible Table retains full names. Axis collision handling does not mean records are missing.", "The browser owner verifies light/dark contrast: necessary graphics at least 3:1 against the actual background and text at least 4.5:1."],
  designEn: { whenToUse: ["Real values in shared units need graphical comparison with reachable numeric equivalents."], avoid: ["Mixed units, guessed results, connecting unavailable values as a reliable trend, or relying on color alone."], composition: ["Public Recharts primitives with current Table and Empty; one rows/series projection."], stateOwner: { library: ["Same-source projection, visible equivalent table, series shapes and basic naming."], application: ["Data, units, truth, state content and custom plotting."] }, responsive: ["A centralized 12em plot height can be overridden. The table scrolls and wraps without cutting actual values."], customization: ["Existing chart1..5 semantic colors, local plot roles and public renderPlot; no separate chart palette."] },
  design: { methods: ["名实相符", "相成相制", "布白有用"], whenToUse: ["真实共享量纲数据需要图形比较，且等价值可达。"], avoid: ["混合量纲、猜测结果、把缺值连成可靠趋势或仅靠颜色。"], composition: ["Recharts公开原语 + 当前Table/Empty；同一rows/series投影。"], stateOwner: { library: ["同源投影、可见等价表、系列形态和基础名称。"], application: ["数据、量纲、真实性、状态文字与自定义图形。"] }, responsive: ["图高集中12em可覆写，表格原生滚动/换行；不裁掉实际值。"], customization: ["chart1..5语义角色；局部plot roles与公开renderPlot，不另造图表调色板。"] },
} satisfies ComponentMeta;
