import type { ComponentMeta } from "@/lib/types";

export default {
  title: "日期时间 DateTimePicker", titleEn: "DateTimePicker",
  description: "编辑完整的当地墙上日期与时间，或应用日历与时间草稿。", descriptionEn: "Edit complete local wall-clock date/time, or apply calendar and time drafts.",
  category: "日期与时间", source: "local", layer: "pattern", exports: ["DateTimePicker"], keywords: ["datetime-local", "日期时间", "wall-clock", "time"],
  decisions: "value 是 YYYY-MM-DDTHH:mm[:ss] 的无时区 wall-clock 文本。它不表示 UTC 瞬间；时区、DST、业务可用时段由应用决定。空时间不会自动补当前时间。",
  decisionsEn: "value is unzoned YYYY-MM-DDTHH:mm[:ss] wall-clock text, not a UTC instant. The application owns timezone, DST, and availability rules. Empty time never becomes the current time automatically.",
  api: [{ name: "DateTimePicker", description: "真实 datetime-local Input 与日期/时间草稿组合。", descriptionEn: "A real datetime-local input composed with calendar and time drafts.", props: [
    { name: "value / onValueChange", type: "string | undefined / (value, event) => void", description: "受控完整本地日期时间；有效年份 1–9999、时间 00:00–23:59，可带秒。带时区或不完整外部字符串拒绝；清除请求 undefined。", descriptionEn: "Controlled complete local date/time: years 1–9999, time 00:00–23:59, optional seconds. Zoned or incomplete external strings are rejected; clearing requests undefined." },
    { name: "name / form", type: "string", description: "仅确认的 datetime-local input 参与 FormData；日历与时间草稿不具提交 name。Field 可提供 name。", descriptionEn: "Only the confirmed datetime-local input submits. Calendar and time drafts have no submission names. Field may provide the name." },
    { name: "disabled / readOnly", type: "boolean", default: "false", description: "阻止原生编辑与展开修改；Field disabled 同样约束动作。只读值提交，禁用值不提交。", descriptionEn: "Block native editing and popup changes, including Field disabled. Read-only values submit; disabled values do not." },
    { name: "inputProps", type: "Input props except owned value/type/name/form/state", description: "真实输入的 min/max/step/required/ARIA/events/ref/render；step 同时交给草稿 time Input。onChange 可取消原生编辑请求。", descriptionEn: "Native min, max, step, required, ARIA, events, refs, and render. step also reaches the time draft. onChange can cancel native edit requests." },
    { name: "calendarProps", type: "CalendarProps except owned selection props", description: "声明日期禁用与导航边界。native min/max 与日历规则及草稿应用校验需调用方同步；库不从 datetime 边界猜禁用日期。", descriptionEn: "Declare disabled dates and navigation bounds. Synchronize native min/max, calendar rules, and draft-apply validation in the caller; datetime bounds do not imply disabled calendar days." },
    { name: "render / ref / className / style / ARIA / events", type: "div composition props", description: "组合根出口；实际输入出口通过 inputProps 定制。", descriptionEn: "Composition root outlet; customize the actual input through inputProps." },
  ] }],
  keyboard: [{ keys: "Tab / Shift+Tab", description: "经过真实日期时间输入与展开入口，展开后到日期、时间与动作。", descriptionEn: "Move through the native input and trigger; while open, reach calendar, time, and actions." }, { keys: "Calendar keys", description: "仅改变日期草稿；时间保持真实输入值。", descriptionEn: "Change only the date draft; time retains its real input value." }, { keys: "Escape", description: "退出本次草稿，回到触发入口。", descriptionEn: "Leave the current draft and return to its trigger." }],
  notes: ["应用仅在日期与时间完整时可用，点击后仍由调用方接受值。", "原生 min/max/step 校验与业务可用性是独立事实；回调不是保存成功。", "浏览器显示格式可随用户环境变化，提交保持无时区的本地文本。"],
  notesEn: ["Apply is available only with complete date and time; the caller still accepts the value.", "Native min/max/step validation and business availability are independent. A callback is not successful persistence.", "The browser's display may vary by environment; submission remains unzoned local text."],
  design: { methods: ["名实相符", "进退相承", "相成相制"], composition: ["Field + FieldLabel + DateTimePicker + FieldDescription / FieldError"], stateOwner: { library: ["展开、日期/时间草稿、键盘与焦点"], application: ["确认 wall-clock 文本、时区/DST 规则、约束与提交结果"] }, responsive: ["一套几何，跟随密度轴，紧凑不缩小文字；内部焦点与真实粗指针目标"], customization: ["inputProps、calendarProps、组合根与现有主题"] }, designEn: {"composition":["Field + FieldLabel + DateTimePicker + FieldDescription / FieldError"],"stateOwner":{"library":["Opening, date/time drafts, keyboard, and focus."],"application":["Confirmed wall-clock text, zone/DST rules, constraints, and submission outcomes."]},"responsive":["Five control/text profiles, internal focus, and actual coarse-pointer targets."],"customization":["inputProps, calendarProps, composition root, and existing theme."]},
} satisfies ComponentMeta;
