import type { ComponentMeta } from "@/lib/types";
export default {
  title: "比较表 Table", titleEn: "Table", description: "原生二维关系与完整比较列。", descriptionEn: "Native two-dimensional relationships with complete comparison columns.",
  category: "数据展示", layer: "pattern", source: "local", exports: ["TableContainer", "Table", "TableCaption", "TableHeader", "TableBody", "TableFooter", "TableRow", "TableHead", "TableCell"],
  decisions: "原生表格保留比较关系，外部容器承接横向容量。行占位与单元格内距消费独立角色；疏密取值是预设。", decisionsEn: "Native table structure preserves comparison; the container handles horizontal capacity. Row occupancy and cell padding consume independent roles; density values are presets.",
  design: { methods: ["名实相符", "布白有用"], whenToUse: ["多个对象需要按共同维度比较。"], avoid: ["单一对象名称值关系用 DescriptionList；长阅读正文用 Typography。"], stateOwner: { library: ["原生二维结构、表头关系与滚动容量。"], application: ["数据、表名、排序、错误、未知与空结果。"] }, responsive: ["横向滚动保留完整比较列，不改成丢维度的卡片。"] }, designEn: {"whenToUse":["Compare multiple objects along shared dimensions."],"avoid":["Use DescriptionList for one object's names/values and Typography for long reading."],"stateOwner":{"library":["Native two-dimensional structure, header relationships, and scrolling capacity."],"application":["Data, table names, sorting, errors, unknown, and empty results."]},"responsive":["Horizontal scrolling retains complete comparison columns instead of cards losing dimensions."]},
  keywords: ["grid", "comparison", "比较", "表格", "比较表", "对照"],
  api: [
    { name: "TableContainer", description: "表格的纸与横向滚动容器。", descriptionEn: "The table's surface and horizontal scroll container.", props: [{ name: "framed", type: "boolean", default: "true", description: "false：表格放在已有的一张纸上（Card、面板），不再铺线、底与圆角；贴着承载面的边放置，由承载面裁切圆角。", descriptionEn: "false places the table on an existing surface such as a Card, without its own line, fill, or radius. Set it flush with the host, which clips the corners." }, { name: "tabIndex / aria-label / render / ref / native props", type: "useRender.ComponentProps<div>", default: "tabIndex=0", description: "ref 属于容器；允许键盘滚动。", descriptionEn: "Ref targets the container; keyboard scrolling remains available." }] },
    { name: "Table / TableCaption / TableHeader / TableBody / TableFooter / TableRow", description: "table / caption / thead / tbody / tfoot / tr。", descriptionEn: "Native table / caption / thead / tbody / tfoot / tr.", props: [{ name: "children / render / ref / native props", type: "useRender.ComponentProps<native table part>", description: "属性属于真实元素；caption 命名整张表。", descriptionEn: "Props reach actual elements; caption names the table." }] },
    { name: "TableHead", description: "th；应用提供排序状态。", descriptionEn: "A th with application-owned sort state.", props: [{ name: "scope", type: '"col" | "row" | "colgroup" | "rowgroup"', default: '"col"', description: "行标题用 row；复杂表格可用 id/headers。", descriptionEn: "Use row for row headers; complex tables may use id/headers." }, { name: "aria-sort / children / native props", type: "native th props", description: "排序交应用 Button 组合，库不重排 rows。", descriptionEn: "Compose an application Button to sort; the library never reorders rows." }] },
    { name: "TableCell", description: "td，零值原样呈现。", descriptionEn: "A td that preserves zero.", props: [{ name: "colSpan / rowSpan / headers / render / ref / native props", type: "useRender.ComponentProps<td>", description: "显式提供跨列和关联表头，不隐藏比较列。", descriptionEn: "Supply spans and header associations explicitly; comparison columns are not hidden." }] },
  ], notes: ["空结果可在完整表头下提供跨列单元格；数据与排序由应用提供。", "一个范围只铺一张纸：表格进 Card 时用 framed={false}，不要在卡片里再套一层边框。"], notesEn: ["Empty results may use a spanning cell below complete headers; data and sorting belong to the application.", "One region, one surface: inside a Card use framed={false} rather than nesting a second border."],
} satisfies ComponentMeta;
