import type { ComponentMeta } from "@/lib/types";

export default {
  title: "按钮 Button",
  titleEn: "Button",
  description: "触发有明确对象与后果的动作；状态由调用方持有。",
  descriptionEn: "Trigger a named action with a clear object and consequence. The caller owns its state.",
  decisions: "按钮只触发动作，忙碌是它唯一的状态：忙碌时保留焦点并阻止重复触发。成功、失败与结果未知是另一件事实，由提示组件表达（就地说明用 Alert，短暂反馈用 Toast，字段错误用 FieldError）；后果与确认属于 AlertDialog。色调不代表授权。",
  decisionsEn: "A button only triggers an action, and busy is its only state: while busy it retains focus and blocks repeated activation. Success, failure and an unknown result are separate facts expressed by feedback components (Alert in place, Toast for brief feedback, FieldError for a field); consequences and confirmation belong to AlertDialog. Tone never grants permission.",
  design: {
    methods: ["名实相符", "相成相制", "进退相承", "随境取度"],
    whenToUse: ["执行有对象与后果的命令、提交表单或停止当前任务。"],
    avoid: ["导航用原生链接。", "把结果写进按钮：忙碌结束不等于成功，失败与结果未知用 Alert、Toast 或 FieldError 表达。"],
    composition: ["有不可逆后果的动作：按钮只是入口，打开 AlertDialog（或 ConfirmAction），后果写在对话框的说明里；确认条件、权限与远端核实属于应用。", "按下后保持的二态（已选中、已开启）用 Toggle；几个里选一个用 SegmentedControl，可多选用 ToggleGroup。Button 只触发动作，不持有选中。"],
    stateOwner: {
      library: ["原生与非原生命令语义、焦点、忙碌时的激活保护与读屏说法。"],
      application: ["对象、范围、后果、权限、请求事实、核实、恢复与取消后台任务。"],
    },
    responsive: ["尺寸按位置选择；长标签可换行增高，图标形态保留同档几何；触摸命中区独立于外观。"],
    customization: ["variant、tone、size 与 shape 分别选择呈现、后果、尺寸与内容形态。"],
  }, designEn: {"whenToUse":["Run a command with an object and consequence, submit a form, or stop the current task."],"avoid":["Use native links for navigation.","Writing the result into the button: the end of busy does not establish success; express failure and unknown results with Alert, Toast or FieldError."],"composition":["For an irreversible action the button is only the entry: it opens AlertDialog (or ConfirmAction), whose description states the consequence. Applications own confirmation criteria, permissions, and remote verification.","A two-state fact that persists after pressing (selected, on) is a Toggle; one of several is SegmentedControl, several of several is ToggleGroup. Button triggers an action and holds no selection."],"stateOwner":{"library":["Native and non-native command semantics, focus, and the activation guard and screen-reader wording while busy."],"application":["Objects, scope, consequences, permissions, request facts, verification, recovery, and background cancellation."]},"responsive":["Choose dimensions for position; long labels may wrap and grow, icons retain matching geometry, and touch targets remain separate from appearance."],"customization":["variant, tone, size, and shape independently select presentation, consequence, dimensions, and content form."]},
  category: "通用",
  layer: "primitive",
  source: "local",
  exports: ["Button", "ButtonPrimitive", "buttonVariants"],
  keywords: ["button", "按钮", "操作", "提交", "loading", "忙碌", "加载中", "危险动作"],
  api: [
    {
      name: "Button",
      description: "默认渲染 type=button 的原生按钮，透传原生属性、ref、事件和派生 data-slot。状态不会自行推进。",
      descriptionEn: "Renders a native type=button control by default and forwards native attributes, refs, events, and derived data-slot values. It never advances its own operation state.",
      props: [
        { name: "variant", type: '"solid" | "bordered" | "quiet"', default: '"solid"', description: "填充、边框或无边框的表达，不表示权限。", descriptionEn: "Filled, bordered, or borderless presentation; it does not express permission." },
        { name: "tone", type: '"neutral" | "danger"', default: '"neutral"', description: "色调。danger 表示动作有不可逆的后果，只改变颜色；后果说明与确认不由按钮承载，用 AlertDialog 或 ConfirmAction。", descriptionEn: "Tone. danger marks an action with an irreversible consequence and changes color only; the consequence text and confirmation are not carried by the button. Use AlertDialog or ConfirmAction." },
        { name: "size", type: '"xs" | "sm" | "md" | "lg" | "xl"', default: '"md"', description: "按所在位置选尺寸，与强调独立。", descriptionEn: "Choose by position, independently of emphasis." },
        { name: "shape", type: '"label" | "icon"', default: '"label"', description: "图标是形态；icon 必须有 aria-label 或 aria-labelledby。", descriptionEn: "Icon is a shape, not another size. Supply aria-label or aria-labelledby for it." },
        { name: "loading", type: "boolean", default: "false", description: "调用方持有的事实：这个动作正在执行。显示转动的记号、设置 aria-busy、保留焦点并阻止重复触发；按钮不启动请求，也不推断何时结束。", descriptionEn: "A caller-owned fact: this action is running. Shows a spinning mark, sets aria-busy, retains focus and blocks repeat activation; the button starts no request and never infers when it ends." },
        { name: "disabled", type: "boolean", default: "false", description: "动作不可用，退出 Tab 顺序；可以与 loading 共存。", descriptionEn: "Makes the action unavailable and removes it from the tab order. It may coexist with loading." },
        { name: "render", type: "ReactElement | (props, state) => ReactElement", description: "Base UI 组合入口，可渲染其他命令载体或触发器；保留真实语义。", descriptionEn: "The Base UI composition entry for another command carrier or trigger. Preserve its actual semantics." },
        { name: "nativeButton", type: "boolean", default: "true", description: "非 button 命令载体设为 false，仍使用按钮语义；导航使用原生 a + buttonVariants。", descriptionEn: "Set false for a non-button command carrier; it retains button semantics. Use a native anchor with buttonVariants for navigation." },
      ],
    },
    { name: "buttonVariants", description: "与 Button 同一套尺寸、形态、强调和色调，用于保留原生链接等元素语义的组合。", descriptionEn: "The same size, shape, emphasis, and tone styles for compositions that retain native element semantics, such as links." },
    { name: "ButtonPrimitive", description: "Base UI 无障碍原语；应用优先使用 Button。", descriptionEn: "The Base UI accessibility primitive. Prefer Button in applications." },
  ],
  keyboard: [
    { keys: "Enter / Space", description: "触发可用动作；忙碌时不触发。", descriptionEn: "Activate an available action. A busy action does not activate." },
    { keys: "Tab / Shift+Tab", description: "移入或移出焦点；忙碌时保留位置，disabled 退出 Tab 顺序。", descriptionEn: "Move focus. A busy action retains its position; disabled actions leave the tab order." },
    { keys: "ArrowUp / ArrowDown", description: "组合菜单或列表触发器按原语操作；忙碌时阻止展开。", descriptionEn: "Follow the primitive's menu or list trigger behavior. A busy trigger does not open." },
  ],
  notes: [
    "危险色调只是色调，不代表授权，也不替代确认；需要用户知道后果再决定时用 AlertDialog。",
    "忙碌时动作的可访问名称不变；「进行中」通过 description 与不可见的 live region 告诉读屏，按钮旁没有可见的状态文字。文字形态在名称后加转动的记号，图标形态由记号暂时替下自己的图形。",
    "state（waiting / in-progress / unknown / failed）已移除，改为 loading。原来写在按钮旁的失败与结果未知，改由 Alert、Toast、FieldError 或 StatusDot 表达。",
    "导航使用原生 a / Link + buttonVariants；nativeButton=false 的 Button 仍是命令语义。",
    "小控件通过 touch-target 扩大命中区到本库 44px 目标，密度与外观尺寸不改变这一目标。",
    "实心入口与父表面对比不足时，消费组合通过 className 添加可辨认边界，并使用同档 padding-bordered；同底色边界示例展示这一入口，组件不读取 DOM 推断承载面。",
  ],
  notesEn: [
    "Danger is only a tone: it grants no permission and replaces no confirmation. Use AlertDialog when the user must know the consequence before deciding.",
    "While busy the action's accessible name stays unchanged; “In progress” reaches screen readers through a description and an invisible live region, and no visible status text sits beside the button. A label button adds a spinning mark after its name; on an icon button the mark temporarily stands in for its glyph.",
    "state (waiting / in-progress / unknown / failed) is removed in favour of loading. Failure and unknown results formerly written beside the button are expressed by Alert, Toast, FieldError or StatusDot.",
    "Use a native anchor or router Link with buttonVariants for navigation. A nativeButton=false Button remains a command.",
    "touch-target expands small controls to the library's 44px touch target without changing visual dimensions or shrinking it with density.",
    "When a solid action lacks contrast with its parent, the consumer adds a visible boundary through className and uses the matching padding-bordered profile. The same-surface example demonstrates this entry; the component does not inspect the DOM to infer its surface.",
  ],
} satisfies ComponentMeta;
