import type { ComponentMeta } from "@/lib/types";

export default {
  title: "候选输入 Combobox", titleEn: "Combobox",
  description: "筛选候选并确认一个或一组值，查询文字与选择事实分别持有。", descriptionEn: "Filter candidates and confirm one value or a set, with query text separate from selection.",
  category: "表单", source: "local", layer: "pattern", exports: ["Combobox", "ComboboxControl", "ComboboxInput", "ComboboxTrigger", "ComboboxClear", "ComboboxValue", "ComboboxChips", "ComboboxChip", "ComboboxPopup", "ComboboxList", "ComboboxItem", "ComboboxEmpty", "ComboboxPrimitive"], keywords: ["combobox", "候选", "filter", "搜索选择"],
  decisions: "value 是确认候选，inputValue 是过滤草稿。清空过滤文字继续保留候选，明确清除选择才请求空值；自由文本值用 Autocomplete。候选很多且要选几个时用 multiple；候选少而需要一眼看全用 CheckboxGroup，值不来自候选用 TagInput。",
  decisionsEn: "value is the confirmed candidate; inputValue is the filter draft. Emptying the query preserves selection. Explicit Clear requests an empty selection. Use Autocomplete for free text. Use multiple to pick several from many candidates; use CheckboxGroup when few options should all stay visible, and TagInput when values do not come from candidates.",
  api: [{ name: "Combobox", description: "公开 Base UI 候选上下文，默认单值；不强加业务选项。", descriptionEn: "A public Base UI candidate context, single-value by default, with caller-provided options.", props: [
    { name: "multiple", type: "boolean", default: "false", description: "确认一组值：value 为数组，FormData 每个值一条；已选值在编辑边界内成为可单独移除的项。", descriptionEn: "Confirm a set: value is an array with one FormData entry per value; each selected value becomes an individually removable chip inside the edit boundary." },
    { name: "value / defaultValue / onValueChange", type: "Value | null / Value | null / (value, details) => void", description: "受控或非受控确认值。details.cancel() 拒绝变更；回调不表示提交或持久化成功。", descriptionEn: "Controlled or uncontrolled confirmation. details.cancel() rejects changes. A callback does not mean submission or persistence." },
    { name: "inputValue / defaultInputValue / onInputValueChange", type: "string / string / (value, details) => void", description: "独立过滤文字；不序列化成候选值，也不因清空查询清除确认候选。", descriptionEn: "Independent query text. It is not serialized as selection and does not clear confirmation when emptied." },
    { name: "items / itemToStringLabel / itemToStringValue / isItemEqualToValue", type: "Base UI public props", description: "调用方提供候选、可读名称、表单值与身份比较；对象值须定义有意义的名称与提交表示。", descriptionEn: "The caller provides candidates, readable labels, form strings, and identity equality. Define meaningful labels and submission values for objects." },
    { name: "name / form / required / disabled / readOnly", type: "Base UI Root props", description: "Field 命名与错误连接由原语承担；FormData 只提交确认候选。只读保留提交，禁用排除。", descriptionEn: "The primitive connects Field naming and errors. FormData submits confirmed selection only. Read-only submits; disabled is excluded." },
    { name: "open / defaultOpen / onOpenChange", type: "Base UI open props", description: "展开可控；输入、动作、候选项共用一套几何，跟随密度轴。", descriptionEn: "Opening is controllable. Input, actions, and items share one geometry following the density axis." },
  ] }, { name: "ComboboxInput / ComboboxTrigger / ComboboxClear", description: "公开原语复用 Input 原生出口与 Button；事件、ARIA、render 状态与 ref 透传，Field 注册一次。", descriptionEn: "Public primitives compose the native Input outlet and Button. Events, ARIA, render state, and refs forward with one Field registration." }, { name: "ComboboxControl", description: "输入、清除与展开共用的一条编辑边界，候选面以它为锚点；多选时可换行，装下已选项。", descriptionEn: "One edit boundary shared by input, clear, and trigger, anchoring the popup; with multiple it wraps to hold the chips." }, { name: "ComboboxChips / ComboboxChip / ComboboxValue", description: "多选的已选项。Chips 放在 Control 内，包住各项与 Input；Value 以函数子级给出已选数组；Chip 自带移除动作，只读时只显示值。几何与 TagInput 的标签相同。", descriptionEn: "Selected values for multiple. Chips sits inside Control around the chips and Input; Value provides the selected array to a function child; Chip carries its own remove action and shows only the value when read-only. Geometry matches TagInput tags.", props: [{ name: "label (ComboboxChip)", type: "string", description: "移除动作的对象名；children 是纯文字时取 children。", descriptionEn: "The object name for the remove action; defaults to children when they are plain text." }] }, { name: "ComboboxPopup", description: "候选专属 Portal/Positioner/Popup；positionerProps/container 可调整公开定位，层级消费共享 floating-layer。", descriptionEn: "Candidate-specific Portal/Positioner/Popup. positionerProps and container customize positioning; layer order comes from shared floating-layer." }, { name: "ComboboxList / ComboboxItem / ComboboxEmpty", description: "真实候选集合、可选项与调用方空内容；Item.value 是确认候选。", descriptionEn: "Real candidate list, selectable items, and caller-provided empty content. Item.value is a confirmation candidate." }, { name: "ComboboxPrimitive", description: "安装版 Base UI Combobox 命名空间。", descriptionEn: "The installed Base UI Combobox namespace." }],
  keyboard: [{ keys: "ArrowLeft / ArrowRight / Backspace", description: "多选：草稿为空时在已选项与输入之间移动；Backspace 或 Delete 移除聚焦的项。", descriptionEn: "Multiple: with an empty draft, move between chips and the input; Backspace or Delete removes the focused chip." }, { keys: "ArrowDown / ArrowUp", description: "展开并移动候选高亮，尚未确认时不改变提交值。", descriptionEn: "Open and move candidate highlighting without changing the submitted value." }, { keys: "Enter", description: "请求确认高亮候选。", descriptionEn: "Request confirmation of the highlighted candidate." }, { keys: "Escape / Tab", description: "退出候选列表，遵守原语焦点与过滤文字恢复规则。", descriptionEn: "Leave the list using primitive focus and query restoration rules." }],
  notes: ["从当前查询到候选的过滤与空内容必须对应实际数据。", "Popup 的 caller style 最后合并；覆写层级可能改变默认顺序。", "候选浮层表面与高亮采用既有主题预设，焦点信号在盒内。"],
  notesEn: ["Filtering and empty content must reflect the real candidate data.", "Popup caller style merges last; layer overrides can change the default order.", "Popup surfaces and highlights use existing theme presets with internal focus signals."],
  design: { methods: ["名实相符", "相成相制", "进退相承"], composition: ["Field + FieldLabel + Combobox / Input / actions / Popup / List / Item"], stateOwner: { library: ["候选键盘、焦点、非受控查询/确认值"], application: ["候选数据、受控查询/值、错误与提交结果"] }, responsive: ["一套几何，跟随密度轴，紧凑不缩小文字；浮层按可用宽度与高度定位"], customization: ["每部位 render/ref/ARIA/events，公开原语与共享浮层角色"] }, designEn: {"composition":["Field + FieldLabel + Combobox / Input / actions / Popup / List / Item"],"stateOwner":{"library":["Candidate keyboard behavior, focus, and uncontrolled query/confirmed value."],"application":["Candidate data, controlled query/value, errors, and submission outcomes."]},"responsive":["One geometry following the density axis; compact tightens the container, never the text; popup positioning uses available width and height."],"customization":["Per-part render/refs/ARIA/events, public primitives, and shared popup roles."]},
} satisfies ComponentMeta;
