import type { ComponentMeta } from "@/lib/types";

export default {
  title: "候选输入 Combobox", titleEn: "Combobox",
  description: "筛选候选并确认一个值，查询文字与选择事实分别持有。", descriptionEn: "Filter candidates and confirm one value, with query text separate from selection.",
  category: "表单", source: "local", layer: "pattern", exports: ["Combobox", "ComboboxInput", "ComboboxTrigger", "ComboboxClear", "ComboboxPopup", "ComboboxList", "ComboboxItem", "ComboboxEmpty", "ComboboxPrimitive"], keywords: ["combobox", "候选", "filter", "搜索选择"],
  decisions: "value 是确认候选，inputValue 是过滤草稿。清空过滤文字继续保留候选，明确清除选择才请求空值；自由文本值用 Autocomplete。",
  decisionsEn: "value is the confirmed candidate; inputValue is the filter draft. Emptying the query preserves selection. Explicit Clear requests an empty selection. Use Autocomplete for free text.",
  api: [{ name: "Combobox", description: "公开 Base UI 单值候选上下文；不强加业务选项。", descriptionEn: "A public Base UI single-value candidate context with caller-provided options.", props: [
    { name: "value / defaultValue / onValueChange", type: "Value | null / Value | null / (value, details) => void", description: "受控或非受控确认值。details.cancel() 拒绝变更；回调不表示提交或持久化成功。", descriptionEn: "Controlled or uncontrolled confirmation. details.cancel() rejects changes. A callback does not mean submission or persistence." },
    { name: "inputValue / defaultInputValue / onInputValueChange", type: "string / string / (value, details) => void", description: "独立过滤文字；不序列化成候选值，也不因清空查询清除确认候选。", descriptionEn: "Independent query text. It is not serialized as selection and does not clear confirmation when emptied." },
    { name: "items / itemToStringLabel / itemToStringValue / isItemEqualToValue", type: "Base UI public props", description: "调用方提供候选、可读名称、表单值与身份比较；对象值须定义有意义的名称与提交表示。", descriptionEn: "The caller provides candidates, readable labels, form strings, and identity equality. Define meaningful labels and submission values for objects." },
    { name: "name / form / required / disabled / readOnly", type: "Base UI Root props", description: "Field 命名与错误连接由原语承担；FormData 只提交确认候选。只读保留提交，禁用排除。", descriptionEn: "The primitive connects Field naming and errors. FormData submits confirmed selection only. Read-only submits; disabled is excluded." },
    { name: "open / defaultOpen / onOpenChange / size", type: "Base UI open props / 'xs' | 'sm' | 'md' | 'lg' | 'xl'", default: "size: 'md'", description: "展开可控；输入、动作、候选项同档 control/text。multiple 固定 false。", descriptionEn: "Opening is controllable. Input, actions, and items share one control/text profile. multiple is false." },
  ] }, { name: "ComboboxInput / ComboboxTrigger / ComboboxClear", description: "公开原语复用 Input 原生出口与 Button；事件、ARIA、render 状态与 ref 透传，Field 注册一次。", descriptionEn: "Public primitives compose the native Input outlet and Button. Events, ARIA, render state, and refs forward with one Field registration." }, { name: "ComboboxPopup", description: "候选专属 Portal/Positioner/Popup；positionerProps/container 可调整公开定位，层级消费共享 floating-layer。", descriptionEn: "Candidate-specific Portal/Positioner/Popup. positionerProps and container customize positioning; layer order comes from shared floating-layer." }, { name: "ComboboxList / ComboboxItem / ComboboxEmpty", description: "真实候选集合、可选项与调用方空内容；Item.value 是确认候选。", descriptionEn: "Real candidate list, selectable items, and caller-provided empty content. Item.value is a confirmation candidate." }, { name: "ComboboxPrimitive", description: "安装版 Base UI Combobox 命名空间。", descriptionEn: "The installed Base UI Combobox namespace." }],
  keyboard: [{ keys: "ArrowDown / ArrowUp", description: "展开并移动候选高亮，尚未确认时不改变提交值。", descriptionEn: "Open and move candidate highlighting without changing the submitted value." }, { keys: "Enter", description: "请求确认高亮候选。", descriptionEn: "Request confirmation of the highlighted candidate." }, { keys: "Escape / Tab", description: "退出候选列表，遵守原语焦点与过滤文字恢复规则。", descriptionEn: "Leave the list using primitive focus and query restoration rules." }],
  notes: ["从当前查询到候选的过滤与空内容必须对应实际数据。", "Popup 的 caller style 最后合并；覆写层级可能改变默认顺序。", "候选浮层表面与高亮采用既有主题预设，焦点信号在盒内。"],
  notesEn: ["Filtering and empty content must reflect the real candidate data.", "Popup caller style merges last; layer overrides can change the default order.", "Popup surfaces and highlights use existing theme presets with internal focus signals."],
  design: { methods: ["名实相符", "相成相制", "进退相承"], composition: ["Field + FieldLabel + Combobox / Input / actions / Popup / List / Item"], stateOwner: { library: ["候选键盘、焦点、非受控查询/确认值"], application: ["候选数据、受控查询/值、错误与提交结果"] }, responsive: ["五档 control/text，浮层按可用宽度与高度定位"], customization: ["每部位 render/ref/ARIA/events，公开原语与共享浮层角色"] }, designEn: {"composition":["Field + FieldLabel + Combobox / Input / actions / Popup / List / Item"],"stateOwner":{"library":["Candidate keyboard behavior, focus, and uncontrolled query/confirmed value."],"application":["Candidate data, controlled query/value, errors, and submission outcomes."]},"responsive":["Five control/text profiles; popup positioning uses available width and height."],"customization":["Per-part render/refs/ARIA/events, public primitives, and shared popup roles."]},
} satisfies ComponentMeta;
