import type { ComponentMeta } from "@/lib/types";

export default {
  title: "组合框 Combobox",
  description: "可输入筛选的选择器：从较长的列表中选一项或多项。只需要输入建议、不强制选中时用 Autocomplete。",
  category: "表单",
  source: "coss",
  exports: [
    "Combobox",
    "ComboboxInput",
    "ComboboxPopup",
    "ComboboxList",
    "ComboboxItem",
    "ComboboxEmpty",
    "ComboboxGroup",
    "ComboboxGroupLabel",
    "ComboboxCollection",
    "ComboboxChips",
    "ComboboxChip",
    "ComboboxChipsInput",
    "ComboboxValue",
    "ComboboxStatus",
  ],
  keywords: ["combobox", "组合框", "可搜索下拉", "多选", "标签选择", "autocomplete select"],
  api: [
    {
      name: "Combobox",
      description: "根组件（Base UI Combobox.Root）。",
      props: [
        { name: "items", type: "T[] | { value, items }[]", description: "选项数据；分组时传 { value, items } 数组。" },
        { name: "value / defaultValue / onValueChange", type: "T | T[] | null", description: "受控 / 非受控的选中值。" },
        { name: "inputValue / onInputValueChange", type: "string", description: "受控的输入文字，用于远程搜索。" },
        { name: "multiple", type: "boolean", default: "false", description: "多选，配合 ComboboxChips 显示已选项。" },
        { name: "filter", type: "((item, query) => boolean) | null", description: "自定义筛选；远程搜索时传 null 关闭本地筛选。" },
        { name: "itemToStringLabel", type: "(item) => string", description: "对象选项的显示文字；含 label 字段时可省略。" },
        { name: "autoHighlight", type: "boolean", default: "false", description: "输入时自动高亮第一个匹配项，回车即可选中。" },
        { name: "name / required / disabled", type: "string / boolean", description: "表单字段与状态。" },
      ],
    },
    {
      name: "ComboboxInput",
      description: "输入框，外观同 Input。",
      props: [
        { name: "size", type: '"sm" | "default" | "lg"', default: '"default"', description: "尺寸。" },
        { name: "showTrigger", type: "boolean", default: "true", description: "末端的展开按钮。" },
        { name: "showClear", type: "boolean", default: "false", description: "有值时显示清除按钮（替换展开按钮）。" },
        { name: "startAddon", type: "ReactNode", description: "前置图标，例如搜索图标。" },
      ],
    },
    { name: "ComboboxPopup", description: "弹出层，宽度至少与输入框相同。" },
    { name: "ComboboxList / ComboboxItem", description: "列表与选项；List 的 children 可以是 (item) => ReactNode。触屏设备上行高 44px。" },
    { name: "ComboboxEmpty / ComboboxStatus", description: "无匹配时的提示；加载中、结果数等状态文字（以 aria-live 播报）。" },
    { name: "ComboboxGroup / ComboboxGroupLabel / ComboboxCollection / ComboboxSeparator", description: "分组展示。" },
    { name: "ComboboxChips / ComboboxChip / ComboboxChipsInput / ComboboxValue", description: "多选输入：已选项以标签显示，可逐个移除。" },
    { name: "useComboboxFilter", description: "Base UI 的本地化筛选工具（contains、startsWith）。" },
  ],
  keyboard: [
    { keys: "↓ / ↑", description: "打开列表并在选项间移动。" },
    { keys: "Enter", description: "选中高亮项。" },
    { keys: "Esc", description: "关闭列表；再次按下清空输入。" },
    { keys: "Backspace", description: "多选时输入为空则移除最后一个标签。" },
    { keys: "← →", description: "多选时在标签之间移动焦点。" },
  ],
  notes: [
    "列表较短（十项以内）且不需要搜索时用 Select。",
    "单选时若希望打开后直接输入新关键词，用受控的 inputValue，在 onOpenChange 里清空。",
    "远程搜索时设置 filter={null}，用 ComboboxStatus 播报「正在搜索」等状态。",
    "多选标签的移除按钮名称来自 UI 语言（默认「移除」）。",
    "移除按钮继承所在 ComboboxChip 的 aria-label，所以标签的 aria-label 要写成动作加内容（如「移除 生产环境」），否则读屏只能听到一串相同的「移除」。",
  ],
} satisfies ComponentMeta;
