// Regenerates src/index.ts from the files in src/components. Safe to rerun.
import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const names = readdirSync(join(root, "src/components"))
  .filter((file) => /\.tsx?$/.test(file))
  .map((file) => file.replace(/\.tsx?$/, ""))
  .sort();
const lines = [
  "// Generated by scripts/gen-index.mjs — do not edit by hand.",
  '// Per-component entry points: "@qingye_lab/ui/components/<name>".',
  'export { cn } from "./utils";',
  'export * from "./locale";',
  'export * from "./floating-layer";',
  'export * from "./hooks/use-copy-to-clipboard";',
  'export * from "./hooks/use-media-query";',
  ...names.map((name) => `export * from "./components/${name}";`),
  "",
];
writeFileSync(join(root, "src/index.ts"), lines.join("\n"));
console.log(`src/index.ts: ${names.length} components`);
