import type { ComponentMeta } from "@/lib/types";

export default {
  title: "数据表格 DataTable",
  description: "基于 TanStack Table 的完整列表：排序、搜索、分页、行选择、批量操作、列显示切换与加载态。既可在客户端处理数据，也可交给服务端分页排序。",
  category: "数据展示",
  source: "local",
  exports: ["DataTable", "type ColumnDef", "type DataTableBulkContext", "type DataTableInstance"],
  keywords: ["data table", "datatable", "数据表格", "列表", "分页", "排序", "tanstack"],
  api: [
    {
      name: "DataTable",
      description: "泛型组件 DataTable<TData>。所有状态都支持受控（传值 + onXChange）与非受控。需要安装可选依赖 @tanstack/react-table。",
      props: [
        { name: "data", type: "TData[]", description: "行数据；服务端分页时为当前页。" },
        { name: "columns", type: "ColumnDef<TData>[]", description: "列定义。meta 支持 label（列菜单名称）、align（\"start\" | \"center\" | \"end\"）、headerClassName、cellClassName。" },
        { name: "getRowId", type: "(row, index) => string", description: "稳定的行 id，跨排序、分页、刷新保持选择。" },
        { name: "label", type: "string", default: "\"数据表格\"", description: "表格的无障碍名称。" },
        { name: "enableGlobalFilter", type: "boolean", default: "true", description: "显示搜索框，按所有列筛选。" },
        { name: "searchPlaceholder", type: "string", default: "\"搜索表格\"", description: "搜索框的占位文字，同时作为它的无障碍名称。" },
        { name: "globalFilter / onGlobalFilterChange", type: "string / (value) => void", description: "受控搜索词。" },
        { name: "collationLocale", type: "string", description: "文本列的排序语言标签（如 \"zh-CN\"）。默认取 <html lang>，因此中文按拼音而非码点排序；数字与日期列不受影响。" },
        { name: "columnFilters / onColumnFiltersChange", type: "ColumnFiltersState", description: "受控列筛选，常与 toolbar 中的自定义筛选配合。" },
        { name: "enableSorting", type: "boolean", default: "true", description: "点击表头排序；列上 enableSorting: false 可单独关闭，Shift 点击多列排序。" },
        { name: "sorting / defaultSorting / onSortingChange", type: "SortingState", description: "排序状态。" },
        { name: "enablePagination", type: "boolean", default: "true", description: "关闭后显示全部行，不渲染分页栏。" },
        { name: "pagination / onPaginationChange", type: "PaginationState", description: "受控页码与每页行数。" },
        { name: "defaultPageSize", type: "number", default: "10", description: "非受控时的初始每页行数。" },
        { name: "pageSizeOptions", type: "number[]", default: "[10, 20, 50]", description: "每页行数选项。" },
        { name: "manualPagination / manualSorting / manualFiltering", type: "boolean", default: "false", description: "交给服务端处理，表格按原样显示 data。" },
        { name: "rowCount", type: "number", description: "服务端总行数，用于页数与汇总。" },
        { name: "enableRowSelection", type: "boolean | (row) => boolean", default: "false", description: "添加复选框列；函数可按行禁用。" },
        { name: "rowSelection / defaultRowSelection / onRowSelectionChange", type: "RowSelectionState", description: "选中状态，以行 id 为键。" },
        { name: "bulkActions", type: "({ rows, ids, clear, table }) => ReactNode", description: "有选中行时显示在已选计数旁的批量操作。" },
        { name: "enableColumnVisibility", type: "boolean", default: "false", description: "显示列菜单，切换可隐藏的列（列上 enableHiding: false 可固定）。" },
        { name: "columnVisibility / defaultColumnVisibility / onColumnVisibilityChange", type: "VisibilityState", description: "列显示状态。" },
        { name: "toolbar", type: "ReactNode | (table) => ReactNode", description: "放在搜索框后的自定义筛选。" },
        { name: "loading", type: "boolean", default: "false", description: "以骨架行代替表体，并设置 aria-busy。" },
        { name: "empty", type: "ReactNode", description: "无数据时的内容；默认提示“没有匹配的结果”，有搜索词时附清除按钮。" },
        { name: "density", type: '"default" | "compact"', default: '"default"', description: "行高。" },
        { name: "variant", type: '"default" | "card"', default: '"default"', description: "表格样式，同 Table。" },
        { name: "maxHeight", type: "number | string", description: "限制表格高度，表体滚动，表头默认吸顶。" },
        { name: "stickyHeader", type: "boolean", description: "表头吸顶；设置 maxHeight 时默认开启。" },
      ],
    },
  ],
  keyboard: [
    { keys: "Tab", description: "依次聚焦搜索框、表头排序按钮、复选框和分页按钮。" },
    { keys: "Enter / Space", description: "焦点在表头按钮上时切换排序：升序、降序、取消（数字列先降序）。" },
    { keys: "Shift + Enter / Shift + Space", description: "焦点在表头按钮上时把该列追加到已有排序，实现多列排序。" },
    { keys: "Space", description: "焦点在复选框上时切换该行或全部行的选择。" },
  ],
  notes: [
    "传入 getRowId，让选择在排序、翻页和数据刷新后仍然指向同一行。",
    "数字、金额、日期列设置 meta: { align: \"end\" }，表头排序图标随之放到左侧，数值右对齐便于比较。",
    "文本列默认按语言的排序规则（Intl.Collator）比较，中文按拼音排序；用 collationLocale 可覆盖，给列写自己的 sortingFn 也可以。",
    "服务端模式下同时设置 manualPagination、manualSorting（及需要的 manualFiltering）与 rowCount，并在 onXChange 中请求数据，请求期间传 loading。",
    "搜索、筛选或排序变化时自动回到第一页；数据减少导致页码越界时自动退回最后一页。",
    "已选数量通过隐藏的 aria-live 区域播报；排序状态通过表头的 aria-sort 暴露，方向同时写给排序按钮的读屏文本。",
    "受控某个状态时请一并提供对应的 onXChange，否则组件无法把排序、搜索等引起的翻页变化交回给你。",
    "加载态渲染与当前每页行数相同的骨架行，数据到达时表格高度不跳动。",
  ],
} satisfies ComponentMeta;
