import type { ComponentMeta } from "@/lib/types";

export default {
  title: "开关 Switch", titleEn: "Switch", description: "立即改变当前设置的开/关状态。", descriptionEn: "Immediately change the on/off state of a current setting.",
  category: "表单", layer: "primitive", source: "local", exports: ["Switch", "SwitchPrimitive"],
  api: [{ name: "Switch", description: "保持名称稳定，用 aria-checked 表达开与关。", descriptionEn: "Keep names stable and use aria-checked for on/off.", props: [
    { name: "checked / defaultChecked", type: "boolean", description: "受控设置值或非受控初值。", descriptionEn: "Controlled setting or uncontrolled initial value." },
    { name: "onCheckedChange", type: "(checked, eventDetails) => void", description: "立即设置的变化入口；请求与持久化由应用承担。", descriptionEn: "An immediate setting change; the application owns requests and persistence." },
    { name: "disabled / readOnly", type: "boolean", default: "false", description: "禁用不参与 Tab/提交；只读仍可聚焦、提交但不可改变。", descriptionEn: "Disabled excludes tabbing/submission; read-only retains focus/submission without changes." },
    { name: "aria-invalid", type: "boolean | 'true' | 'false'", description: "调用方或 Field 声明无效，保留当前开/关事实。", descriptionEn: "Caller or Field declares invalid while retaining the actual on/off state." },
    { name: "name / value / uncheckedValue / form", type: "string", description: "原语隐藏输入的提交入口；不代表必须等待表单提交才生效。", descriptionEn: "Primitive hidden input submission; this does not require waiting for form submission before taking effect." },
    { name: "render / ref / inputRef / className / style", type: "Base UI composition", description: "根部位与隐藏 input 的组合；渲染 button 时设置 nativeButton。", descriptionEn: "Root and hidden input composition; set nativeButton when rendering a button." },
  ] }, { name: "SwitchPrimitive", description: "完整 Base UI Switch 命名空间，包含 Root 与 Thumb。", descriptionEn: "The complete Base UI Switch namespace, including Root and Thumb." }],
  keyboard: [{ keys: "Tab / Shift+Tab", description: "进入或离开开关。", descriptionEn: "Enter or leave the switch." }, { keys: "Space", description: "立即切换当前设置。", descriptionEn: "Change the current setting immediately." }],
  notes: ["名称不随开关状态改变。", "不支持部分选中；多选或待提交选择用 Checkbox。", "异步保存的等待、未知和失败属于应用，不能用滑块动画表示请求成功。"], notesEn: ["Names stay stable across on/off states.","No partial selection; use Checkbox for multiple or pending selections.","Applications own asynchronous save waiting, unknown, and failure; thumb animation cannot establish request success."],
  decisions: "只有当前设置立即改变时才用 Switch。条款同意、待提交选择和不可逆命令分别使用 Checkbox 或明确的动作与结果反馈。", decisionsEn: "Use Switch only when the current setting changes immediately. Consent, pending selections, and irreversible commands use Checkbox or explicit actions and outcome feedback.",
  design: { methods: ["名实相符", "进退相承"], whenToUse: ["立即生效的二值设置"], avoid: ["待提交选择用 Checkbox", "不可逆命令用 Button", "结果未知时先核实"], composition: ["Field + FieldLabel + Switch + FieldDescription / FieldError"], stateOwner: { library: ["焦点、键盘、非受控 checked"], application: ["当前设置、请求与保存结果、invalid"] }, responsive: ["窄屏保留控件高+4px，命中区不随密度缩小；本批只验桌面"], customization: ["主题填充及前景、同名文字行高、focus宽度"] }, designEn: {"whenToUse":["Binary settings taking effect immediately."],"avoid":["Use Checkbox for pending selections.","Use Button for irreversible commands.","Verify unknown results first."],"composition":["Field + FieldLabel + Switch + FieldDescription / FieldError"],"stateOwner":{"library":["Focus, keyboard, and uncontrolled checked state."],"application":["Current settings, request/save outcomes, and invalid facts."]},"responsive":["Narrow heights retain +4px and density never shrinks hit areas; this batch checked desktop only."],"customization":["Theme fills/foregrounds, matching text line heights, and focus widths."]},
} satisfies ComponentMeta;
