import type { ComponentMeta } from "@/lib/types";
export default {
  title: "工具组 Toolbar", titleEn: "Toolbar", description: "真实分组、方向键焦点与可执行操作。", descriptionEn: "Actual groups, arrow-key focus and operable actions.",
  category: "布局", layer: "pattern", source: "local", exports: ["Toolbar", "ToolbarGroup", "ToolbarButton", "ToolbarLink", "ToolbarSeparator", "ToolbarPrimitive"],
  decisions: "Base UI Toolbar 接管 roving focus 与组禁用；按钮默认组合当前 Button，链接保留导航，应用提供操作名称与选中事实。", decisionsEn: "Base UI Toolbar owns roving focus and group disabling. Buttons compose current Button; links retain navigation; action names and selection facts belong to the application.",
  design: { methods: ["相成相制", "随境取度"], whenToUse: ["持续的相关操作需要一个键盘进入点与方向键导航。"], avoid: ["普通并列按钮用 ButtonGroup；目的地集合用导航链接。"], stateOwner: { library: ["Base UI roving focus、方向、组禁用与事件保护。"], application: ["操作名称、真实选中/禁用状态及执行结果。"] }, responsive: ["横向操作可换行，垂直方向使用对应方向键。"] }, designEn: {"whenToUse":["Persistent related actions need one keyboard entry with arrow navigation."],"avoid":["Use ButtonGroup for ordinary adjacent actions and links for destinations."],"stateOwner":{"library":["Base UI roving focus, orientation, group disabling, and event guards."],"application":["Action names, actual selected/disabled states, and execution outcomes."]},"responsive":["Horizontal actions may wrap; vertical layouts use corresponding arrows."]},
  keywords: ["tools", "action bar", "工具栏", "工具组", "操作栏"],
  api: [
    { name: "Toolbar", description: "Base UI Toolbar.Root。", descriptionEn: "Base UI Toolbar.Root.", props: [{ name: "orientation / loopFocus / disabled / aria-label / render / ref", type: "ToolbarPrimitive.Root.Props", default: 'orientation="horizontal", loopFocus=true', description: "应用为工具组命名；方向决定键盘移动轴。", descriptionEn: "The application names the toolbar; orientation sets the arrow-key axis." }] },
    { name: "ToolbarGroup", description: "命名与禁用一组相关操作。", descriptionEn: "Name and disable related actions together.", props: [{ name: "disabled / aria-label / render / ref / native props", type: "ToolbarPrimitive.Group.Props", description: "禁用事实传给组内真实操作。", descriptionEn: "Disabled state reaches actual controls inside the group." }] },
    { name: "ToolbarButton", description: "真实命令；默认组合 Button。", descriptionEn: "An actual command that composes Button by default.", props: [{ name: "size / variant", type: "ButtonProps[size | variant]", default: 'size="md", variant="quiet"', description: "复用基础层尺寸和表面预设。", descriptionEn: "Reuse foundation size and surface presets." }, { name: "disabled / focusableWhenDisabled / render / ref / nativeButton", type: "ToolbarPrimitive.Button.Props", description: "自定义 render 时提供合法按钮或成熟触发器，保留焦点与事件链。", descriptionEn: "Custom renders must supply a valid button or mature trigger and retain the focus and event chain." }] },
    { name: "ToolbarLink / ToolbarSeparator", description: "真实 a 与方向相关组分界。", descriptionEn: "A real anchor and orientation-aware group separator.", props: [{ name: "href / orientation / render / ref / primitive props", type: "ToolbarPrimitive.Link.Props | ToolbarPrimitive.Separator.Props", description: "链接导航；分隔符不生成操作。", descriptionEn: "Links navigate; separators generate no command." }] },
  ], keyboard: [{ keys: "Tab / Shift+Tab", description: "进入或离开整个工具组。", descriptionEn: "Enter or leave the whole toolbar." }, { keys: "方向键 / Home / End", keysEn: "Arrow keys / Home / End", description: "由 Base UI 按方向移动焦点。", descriptionEn: "Base UI moves focus along the toolbar orientation." }, { keys: "Enter / Space", description: "执行实际命令。", descriptionEn: "Activate the actual command." }],
  notes: ["只为持续的相关操作使用 Toolbar；普通多个按钮可以用 ButtonGroup。"], notesEn: ["Use Toolbar for persistent related operations; ordinary button collections may use ButtonGroup."],
} satisfies ComponentMeta;
