import type { ComponentMeta } from "@/lib/types";
export default {
  title: "确认动作 ConfirmAction", titleEn: "ConfirmAction",
  description: "确认具体对象、版本与变更，内容改变后重新阅读。", descriptionEn: "Confirm a specific object, version, and change; review again when content changes.",
  category: "反馈", source: "local", layer: "pattern", exports: ["ConfirmAction", "ConfirmActionPrimitive"], keywords: ["confirmation", "确认", "snapshot", "保护"],
  decisions: "确认针对打开时的可读快照。任何对象、版本、变更或后果改变都使旧认可失效；重新阅读会清除旧确认文字。onConfirm 只是请求，Promise 完成不会推断成功或自动关闭。",
  decisionsEn: "Confirmation targets the reviewed opening snapshot. Changed identity, version, change, or consequence invalidates prior approval. Reviewing again clears confirmation text. onConfirm is a request; resolving a Promise neither infers success nor closes the dialog.",
  api: [{ name: "ConfirmAction", description: "AlertDialog 与可选 Field/Input 的确认组合；后果是对话框的说明。", descriptionEn: "A confirmation composition of AlertDialog and optional Field/Input; the consequence is the dialog's description.", props: [
    { name: "snapshot", type: "{ objectId: string; objectLabel: string; version: string | number; change: string; consequence: string }", description: "所有字段必需且有意义；比较包含全部字段。打开捕获不可变副本，确认回调只收到仍对应当前事实的已读副本。", descriptionEn: "All fields are required and meaningful; comparisons include every field. Opening captures an immutable copy. Confirmation receives only a reviewed copy that still matches current facts." },
    { name: "title / triggerLabel / actionLabel", type: "ReactNode", description: "调用方提供真实对象与动作文字。后果保持可见并关联实际确认按钮。", descriptionEn: "The caller names the real object and action. Consequences remain visible and linked to confirmation." },
    { name: "onConfirm", type: "(snapshot, event) => void", description: "仅请求动作，不发网络、不拥有结果、不自动关窗。应用通过 loading 表达请求中，通过 children 里的提示组件表达权限、失败或结果未知。", descriptionEn: "Request only: no network, result ownership, or automatic closing. The application expresses a pending request through loading, and permissions, failure and unknown results through feedback components in children." },
    { name: "loading / disabled", type: "boolean / boolean", default: "false / false", description: "loading 表示请求已发出、结果未到：入口与确认动作都显示忙碌并阻止再次请求，保留 Button 的可聚焦 ARIA 禁用；明确 disabled 用原生禁用。返回只关闭界面。", descriptionEn: "loading means the request is sent and its result has not arrived: both the entry and the confirm action show busy and block another request, keeping Button's focusable ARIA-disabled behavior; explicit disabled is native. Back only closes this UI." },
    { name: "confirmationText / confirmationLabel", type: "string / ReactNode", description: "可选准确匹配文字，必须同时给出可见标签；FieldDescription 显示需要的文字。重新阅读或重新打开清旧输入。", descriptionEn: "Optional exact text match with a required visible label. FieldDescription shows the expected text. Reviewing or reopening clears prior input." },
    { name: "open / defaultOpen / onOpenChange", type: "AlertDialog public props", description: "受控或非受控展开，onOpenChange details.cancel() 可拒绝；受控调用方决定是否打开/关闭。", descriptionEn: "Controlled or uncontrolled opening. onOpenChange details.cancel() can reject it; the controlled caller decides opening and closing." },
    { name: "tone", type: "ButtonTone", default: "'danger'", description: "核对输入框读填值控件的一套几何（跟随密度轴）；动作按钮仍用 Button 的尺寸档，因为大小表达位置。tone 表达调用方后果，不赋予权限。", descriptionEn: "The confirmation input follows the one fill-control geometry (density axis); action buttons keep Button size steps because size expresses position. Tone expresses consequences without granting permission." },
    { name: "triggerProps / confirmProps / inputProps / popupProps", type: "Current public component props", description: "定制真实出口的 render/ref/ARIA/events；confirmProps.onClick 的事件取消阻止请求。入口只打开确认，后果在对话框里给出。", descriptionEn: "Customize real outlets' render, refs, ARIA, and events. Canceling confirmProps.onClick blocks a request. The entry only opens the confirmation; the dialog states the consequence." },
    { name: "children", type: "ReactNode", description: "附加真实核对内容或应用提供的状态/恢复入口，位于确认面板。", descriptionEn: "Additional real review content or application-provided state and recovery outlets in the panel." },
  ] }, { name: "ConfirmActionPrimitive", description: "所用安装版 AlertDialog 原语命名空间。", descriptionEn: "The installed AlertDialog primitive namespace." }],
  keyboard: [{ keys: "Enter / Space", description: "打开确认或请求当前快照；失效与阻止状态不触发。", descriptionEn: "Open confirmation or request the current snapshot; invalidated and blocked states do not activate." }, { keys: "Tab / Shift+Tab", description: "在真实模态与确认输入/动作间移动。", descriptionEn: "Move through the real modal, confirmation input, and actions." }, { keys: "Escape / 返回", keysEn: "Escape / Back", description: "退出确认并返回触发入口，不表示取消后台操作。", descriptionEn: "Leave confirmation and return to its trigger without implying background cancellation." }],
  notes: ["内容恢复成旧值也不会自动复活旧认可；必须重新阅读。", "确认次数与结果事实归应用；没有自建超时、假成功或自动重试。", "浮层、尺寸、焦点与后果关联直接消费当前公共组件及集中预设。"],
  notesEn: ["Restoring old content does not revive old approval; review again.", "The application owns action attempts and outcomes. There is no custom timeout, fake success, or automatic retry.", "Layering, sizes, focus, and consequence association use current public components and centralized presets."],
  design: { methods: ["名实相符", "进退相承", "相成相制"], composition: ["ConfirmAction + 明确 snapshot/文字 + 应用 loading/onConfirm；结果用 Alert 或 Toast 表达"], stateOwner: { library: ["展开、已读快照、失效提示、可选确认输入"], application: ["对象、版本、变更、权限、动作状态与结果"] }, responsive: ["一套几何，跟随密度轴，紧凑不缩小文字；模态消费共享可用空间和焦点机制"], customization: ["各公共部件 props、children 与现有主题"] }, designEn: {"composition":["ConfirmAction + explicit snapshot/text + application loading/onConfirm; express the result with Alert or Toast."],"stateOwner":{"library":["Open state, reviewed snapshot, invalidation notice, and optional confirmation input."],"application":["Objects, versions, changes, permissions, action states, and outcomes."]},"responsive":["Five matching control/text profiles; the modal consumes shared space and focus mechanisms."],"customization":["Public part props, children, and existing theme roles."]},
} satisfies ComponentMeta;
