import type { ComponentMeta } from "@/lib/types";
export default {
  title: "两维度的量 Heatmap", titleEn: "Heatmap", description: "两个类别维度上的量，例如「星期 × 时段」的同步热度；单色顺序色阶（第一色由淡到足），可聚焦的格与按需展开的数据表。", descriptionEn: "A quantity over two categorical dimensions, such as sync activity by weekday and hour; a single-hue sequential scale (the first series color, light to full), focusable cells and an on-demand data table.", category: "数据展示", layer: "pattern", source: "local", exports: ["Heatmap"], keywords: ["heatmap", "heat map", "grid", "热力图", "热度", "网格"],
  decisions: "行列都是类别轴，不是数据系列——没有身份要区分，只有量的大小，因此只用一种色相：数据是色，取第一色（花青）与纸调和的 12% 到足色。未知/不适用格用清墨斜线纹，不进色阶，避免与真实的小量值混淆。",
  decisionsEn: "Rows and columns are both categorical axes, not data series — there is no identity to distinguish, only magnitude, so it uses one hue: data is color, the first series color (huaqing) mixed with paper from 12% to full. Unknown/not-applicable cells carry a diagonal ink hatch instead of a scale step, so they are never mistaken for a small real value.",
  api: [{ name: "Heatmap", description: "figure 名称、两个命名的类别轴、单色顺序色阶的网格与同源可见 Table。", descriptionEn: "A named figure, two named categorical axes, a single-hue sequential grid and a visible same-source Table.", props: [
    { name: "label", type: "string", description: "非空真实语义名称。", descriptionEn: "A nonempty semantic name for the actual data." },
    { name: "state", type: '"ready" | "empty" | "unknown" | "not-applicable"', default: '"ready"', description: "真实整图事实；非ready由children表达。", descriptionEn: "The actual chart-wide state. children describe non-data states." },
    { name: "rowLabel / columnLabel / valueLabel", type: "string", description: "行维度、列维度与量各自的名字，例如「时段」「星期」「同步次数」。", descriptionEn: "Names for the row dimension, column dimension and the measured quantity, e.g. \"hour\", \"weekday\", \"syncs\"." },
    { name: "columns", type: "readonly { key: string; label: string }[]", description: "列维度的取值，2 个以上——与数据系列不同，没有身份色上限。", descriptionEn: "The column dimension's values, two or more — unlike a data series, there is no identity-color cap." },
    { name: "rows", type: "readonly ChartRow[]", description: "行维度的取值，2 个以上；每行必须对每个 column.key 给出 finite number 或 {state, label}。", descriptionEn: "The row dimension's values, two or more; every row must supply a finite number or {state, label} for every column key." },
    { name: "formatValue", type: "(value, row, column) => ReactNode", description: "格式化已知数值；默认按 UILocale 数值 Intl。", descriptionEn: "Format known values; defaults to Intl number formatting for UILocale." },
  ] }],
  notes: ["每个格都可聚焦，aria-label 直接给出行、列与数值或未知原因，不依赖悬停就能读到。", "悬停/聚焦读数只增强，不替代可聚焦格自身的名称与数据表。", "相邻格之间 2px 纸色空隙，与柱状、堆叠柱同一机制。", "少于两行或两列会抛出错误：那是 Chart 的 bar，不是网格。"],
  notesEn: ["Every cell is focusable; its aria-label states the row, column and value or unavailable reason directly, reachable without hovering.", "Hover/focus readouts only enhance; they never replace the focusable cell's own name or the data table.", "Adjacent cells carry the same 2px surface-color gap as bars and stacked bars.", "Fewer than two rows or columns throws: that is a Chart bar, not a grid."],
  design: { methods: ["名实相符", "墨分五色"], whenToUse: ["两个类别维度组合出的量需要一眼看出热度分布，例如一周内各时段的同步次数。"], avoid: ["只有一个类别维度（用 Chart bar）；需要精确读出每个数值而不是找热点（用数据表或 Chart）。"], composition: ["手写 CSS 网格 + 当前 Table/Empty；复用 Chart 的 readValue 取值契约。"], stateOwner: { library: ["网格着色、可聚焦名称、可见等价表与基础校验。"], application: ["数据、量纲与真实性。"] }, responsive: ["网格随可用宽度收缩，超宽时横向滚动；表格原生滚动/换行。"], customization: ["第一色的顺序色阶；不另造热力图调色板。"] },
  designEn: { whenToUse: ["A quantity formed by two categorical dimensions needs an at-a-glance heat pattern, e.g. sync counts by hour across a week."], avoid: ["Only one categorical dimension (use Chart bar); reading every exact value rather than spotting hot spots (use a data table or Chart)."], composition: ["A hand-built CSS grid with current Table and Empty; reuses Chart's readValue contract."], stateOwner: { library: ["Grid coloring, focusable naming, the visible equivalent table and basic validation."], application: ["Data, units and truth."] }, responsive: ["The grid shrinks with available width and scrolls horizontally when it would overflow; the table scrolls and wraps natively."], customization: ["The first series color's sequential scale; no separate heatmap palette."] },
} satisfies ComponentMeta;
