import type { ComponentMeta } from "@/lib/types";

export default {
  title: "字段 Field", titleEn: "Field",
  description: "关联一个值的名称、控件、说明与调用方提供的错误。",
  descriptionEn: "Connect one value's name, control, description, and caller-supplied errors.",
  category: "表单", layer: "primitive", source: "local",
  exports: ["Field", "FieldLabel", "FieldDescription", "FieldError", "FieldTitle", "FieldContent", "FieldGroup", "FieldSeparator", "FieldItem", "FieldControl", "FieldValidity"],
  keywords: ["field", "字段", "名称", "错误", "label", "description"],
  decisions: "invalid 与错误内容分别传入。Field 关联名称与错误，不自行校验或推断提交结果。",
  decisionsEn: "Supply invalid and error content separately. Field connects names and errors without validating or inferring submission results.",
  design: {
    methods: ["名实相符", "相成相制", "布白有用", "进退相承"],
    whenToUse: ["一个值需要持续名称、必要说明或就地错误。"],
    avoid: ["placeholder 代替名称；Toast 代替字段错误；超时冒充格式错误。"],
    composition: ["Input 自动注册；原生控件通过 FieldControl 注册。Fieldset 命名共同范围，FieldGroup 只组织间隔。"],
    stateOwner: {library: ["名称、说明和错误的可访问连接；焦点、触及、禁用传播。"], application: ["值、规则、invalid、错误内容、草稿与送达结果。"]},
    responsive: ["长名称与说明可换行；横向内容列可收缩；间距由字段角色决定。"],
    customization: ["className 最后合并，原生属性、状态样式函数、ref 和 render 透传；FieldTitle 不注册成 label。"],
  }, designEn: {"whenToUse":["A value needs a persistent name, necessary explanation, or in-place error."],"avoid":["Placeholders instead of names, Toast instead of field errors, or timeouts presented as format errors."],"composition":["Input registers automatically; FieldControl registers native controls. Fieldset names a shared scope; FieldGroup organizes spacing only."],"stateOwner":{"library":["Accessible name/description/error associations; focus, touched state, and disabled propagation."],"application":["Values, rules, invalid facts, error content, drafts, and delivery outcomes."]},"responsive":["Long names/descriptions wrap, horizontal content columns shrink, and field roles determine spacing."],"customization":["External classes merge last; native props, state styling callbacks, refs, and render forward. FieldTitle does not register as a label."]},
  api: [
    {name: "Field", description: "Base UI Field.Root 的共同上下文；自动校验入口交给完整的 FieldPrimitive。", descriptionEn: "Shared Base UI Field.Root context. Full automatic-validation APIs remain on FieldPrimitive.", props: [
      {name: "orientation", type: '"vertical" | "horizontal"', default: '"vertical"', description: "纵向编辑或横向选项，不改变关联。", descriptionEn: "Vertical editing or a horizontal option; associations stay intact."},
      {name: "invalid", type: "boolean", default: "false", description: "由调用方声明。原生约束、失焦、错误内容不推断此状态。", descriptionEn: "Declared by the caller. Native constraints, blur, and error content do not infer it."},
      {name: "disabled", type: "boolean", default: "false", description: "禁用关联控件，禁用值不参加原生提交。", descriptionEn: "Disables registered controls; disabled values are omitted from native submission."},
      {name: "name / dirty / touched", type: "Base UI Field.Root props", description: "字段名及调用方管理的编辑事实。", descriptionEn: "Field name and caller-managed editing facts."},
      {name: "className / style / render / ref", type: "Base UI Field.Root props", description: "作用于字段根；样式支持状态函数。", descriptionEn: "Applied to the field root; styles support state functions."},
    ]},
    {name: "FieldLabel", description: "自动命名注册控件，支持显式 htmlFor 与原语 nativeLabel/render。", descriptionEn: "Names a registered control; supports explicit htmlFor and primitive nativeLabel/render."},
    {name: "FieldDescription", description: "必要辅助事实；注册到 aria-describedby。", descriptionEn: "Necessary supporting facts registered in aria-describedby."},
    {name: "FieldError", description: "只显示调用方错误，显示时加入 aria-describedby。", descriptionEn: "Shows caller-supplied errors and registers in aria-describedby when visible.", props: [
      {name: "children", type: "ReactNode", description: "显式内容优先；无内容不生成浏览器或 Form 错误。", descriptionEn: "Explicit content takes precedence; no content means no browser or Form error is generated."},
      {name: "errors", type: "ReadonlyArray<{ message?: string } | undefined>", description: "忽略空项、去重；多条用列表。", descriptionEn: "Skips empty entries, deduplicates, and lists multiple messages."},
      {name: "match", type: "boolean | keyof ValidityState", default: "true", description: "保留原语过滤接口；false 隐藏。内容与 invalid 分别由调用方决定。", descriptionEn: "Primitive filtering interface; false hides the message. The caller supplies content and invalid separately."},
    ]},
    {name: "FieldTitle", description: "普通事实标题；用于自命名控件或无输入事实，不是 label。", descriptionEn: "A plain fact heading for self-named controls or facts without input; it is not a label."},
    {name: "FieldContent", description: "横向字段的名称、说明内容列。", descriptionEn: "The name and description column of a horizontal field."},
    {name: "FieldGroup", description: "字段之间的关系间隔，没有 group 语义。", descriptionEn: "Spacing between fields, without group semantics."},
    {name: "FieldSeparator", description: "字段组分界；有文字时两侧线为装饰。", descriptionEn: "A boundary between field groups; flanking lines are decorative when text is supplied."},
    {name: "FieldItem", description: "同一 Field 内某个控件与标签的局部关联。", descriptionEn: "Scopes a particular control and label within one Field."},
    {name: "FieldControl / FieldValidity / FieldPrimitive", description: "直接的原语注册、状态读取与完整 API 出口。", descriptionEn: "Direct primitive outlets for registration, state reading, and the full API."},
  ],
  keyboard: [{keys: "Tab / Shift+Tab", description: "按文档顺序进入控件；点击关联标签聚焦或切换控件。", descriptionEn: "Follow document order; activating an associated label focuses or toggles the control."}],
  notes: [
    "Field 不接受 validate、validationMode、validationDebounceTime、actionsRef。应用用自己的校验过程把结果传入；需要原语自动校验时完整使用 FieldPrimitive。",
    "FieldError 无内容时不渲染。字段外给定内容可以显示，但不会关联别处的控件。",
    "未注册的自命名控件需要显式 aria-labelledby 和 aria-describedby；FieldTitle 不代替这一连接。",
    "共同范围从 components/fieldset 导入 Fieldset / FieldsetLegend；FieldSet / FieldLegend 别名已删除。",
    "样式消费 field-gap、field-group-gap 和文字档；具体数值是集中预设。",
  ],
  notesEn: [
    "Field excludes validate, validationMode, validationDebounceTime, and actionsRef. Pass results from application validation; use the full FieldPrimitive composition for primitive-managed validation.",
    "FieldError renders nothing without supplied content. Standalone content does not associate with another control.",
    "Unregistered self-named controls need explicit aria-labelledby and aria-describedby. FieldTitle does not supply those connections.",
    "Import Fieldset / FieldsetLegend from components/fieldset. FieldSet / FieldLegend aliases have been removed.",
    "Styles consume field-gap, field-group-gap, and text profiles. Their numerical values are centralized presets.",
  ],
} satisfies ComponentMeta;
