import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,rmSync,symlinkSync,renameSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,dirname} from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {loadProject,projectInfo,componentDocs,inside,checkProject,getTheme,updateTheme,validateTheme,themeCss,initProject,readReports,getImpact} from '../dist/index.js';

const config={schemaVersion:1,package:'@qingye_lab/ui',publicEntry:'src/ui.ts',styleEntry:'src/ui.css',theme:{source:'ui.theme.json',generated:'ui.theme.generated.css',mode:'class'},scan:['src'],compositions:[],tokenSources:[],adapters:[],diagnostics:{preset:'personal',mode:'report',report:'.qingye/report.json'}};
const theme={schemaVersion:1,brand:'azure',common:{'--qy-control-md':'2rem'},light:{'--qy-primary':'#174c83','--qy-primary-foreground':'#fff'},dark:{'--qy-primary':'#93c5fd'},compact:{'--qy-control-md':'1.75rem'}};
function fixture(t,{configured=true}={}){
  const root=mkdtempSync(resolve(tmpdir(),'qingye-tooling-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
  const put=(path,value)=>{mkdirSync(dirname(resolve(root,path)),{recursive:true});writeFileSync(resolve(root,path),typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');};
  put('package.json',{name:'actual-app',type:'module',dependencies:{'@qingye_lab/ui':'0.3.2'},scripts:{check:'tsc --noEmit'}});
  put('node_modules/@qingye_lab/ui/package.json',{name:'@qingye_lab/ui',version:'0.3.2',type:'module',exports:{'.':{types:'./index.d.ts',import:'./index.js'},'./components/*':{types:'./components/*.d.ts',import:'./components/*.js'},'./package.json':'./package.json','./catalog.json':'./catalog.json'}});
  put('node_modules/@qingye_lab/ui/index.d.ts','export declare const Button: (props: any) => any;\nexport {Button as Action};\n');
  put('node_modules/@qingye_lab/ui/components/button.d.ts','export declare const Button: (props: any) => any;');
  put('node_modules/@qingye_lab/ui/catalog.json',{schemaVersion:2,version:'0.3.2',components:[{name:'button',exports:['Button','Action'],actualExports:[{name:'Button',owner:'button'},{name:'Action',owner:'button',aliasOf:'Button'}],examples:[{id:'basic',code:'<Button />'}],api:[]}],patterns:[{id:'P01',slug:'editing',states:['failed']}]});
  put('node_modules/@qingye_lab/ui/tokens/semantic.css',':root { --qy-primary: #111; --qy-primary-foreground:#fff; --qy-control-md:2rem; --qy-radius-control:0.5rem; --qy-radius-panel:0.75rem; --qy-panel-padding:1.5rem; --qy-space-2:0.5rem; --qy-duration-fast:140ms; }');
  put('tsconfig.json',{compilerOptions:{module:'ESNext',moduleResolution:'Bundler',baseUrl:'.',paths:{'@local/ui':['src/ui.ts']},jsx:'react-jsx'}});
  put('src/ui.ts','export { Button as ProjectButton } from "@qingye_lab/ui/components/button";');
  put('src/ui.css','');
  put('src/app.tsx','import {ProjectButton} from "@local/ui"; export const App = () => <main><ProjectButton className="grid grid-cols-[1fr_2fr] gap-(--qy-space-2)" style={{width:42}}>Run</ProjectButton></main>;');
  if(configured){put('ui.config.json',config);put('ui.theme.json',theme);put('ui.theme.generated.css',themeCss(theme,'class'));}
  return {root,put,config:structuredClone(config),theme:structuredClone(theme)};
}
function envelope(root){const current=getTheme(root);return {fingerprint:current.fingerprint,generatedFingerprint:current.generatedFingerprint,configFingerprint:current.configFingerprint};}
test('info and docs read actual installed version and resolve aliases/patterns',t=>{const {root}=fixture(t);assert.equal(projectInfo(root).version,'0.3.2');assert.equal(componentDocs(root,'Action').entry.name,'button');assert.equal(componentDocs(root,'P01').entry.slug,'editing');assert.throws(()=>componentDocs(root,'not-real'),/No installed catalog/);});
test('project boundary refuses absolute, traversal and symlink paths',t=>{const {root,put,config}=fixture(t);assert.throws(()=>inside(root,root+'/src/../src/app.tsx'),/escapes/);assert.throws(()=>inside(root,'../outside'),/escapes/);symlinkSync(tmpdir(),resolve(root,'external'));assert.throws(()=>inside(root,'external/probe'),/Symlink/);config.scan=['../other'];put('ui.config.json',config);assert.throws(()=>loadProject(root),/escapes/);});
test('source and generated aliases cannot address the same physical file',t=>{const {root,put,config}=fixture(t);const before=readFileSync(resolve(root,'ui.theme.json'),'utf8');config.theme.generated='./ui.theme.json';put('ui.config.json',config);assert.throws(()=>loadProject(root),/different files/);assert.equal(readFileSync(resolve(root,'ui.theme.json'),'utf8'),before);config.theme.generated='alias.css';symlinkSync(resolve(root,'ui.theme.json'),resolve(root,'alias.css'));put('ui.config.json',config);assert.throws(()=>loadProject(root),/different files/);assert.equal(readFileSync(resolve(root,'ui.theme.json'),'utf8'),before);});
test('theme validates registered tokens, unsafe declarations and reserved brand',t=>{const {root}=fixture(t),project=loadProject(root);assert.equal(validateTheme(project,theme).status,'PASS');for(const replacement of [{...theme,brand:'dark'},{...theme,light:{'--qy-made-up':'1px'}},{...theme,light:{'--qy-primary':'red; color:blue'}},{...theme,light:{'--qy-primary':'url(https://remote)'}},{...theme,light:{'--qy-primary':'var(--qy-missing)'}}])assert.equal(validateTheme(project,replacement).status,'FAIL');});
test('class and attribute CSS keep brand, brightness and density independent',t=>{fixture(t);const css=themeCss(theme,'class');assert.match(css,/html\[data-brand="azure"\]\.dark/);assert.match(css,/html\[data-brand="azure"\]\[data-density="compact"\]/);assert.match(themeCss(theme,'data-theme'),/html\[data-brand="azure"\]\[data-theme="dark"\]/);assert.doesNotMatch(css,/data-theme="azure"/);});
test('theme update is dry by default, applies atomically, conflicts with edits and is idempotent',t=>{const {root,put}=fixture(t),changed={...theme,light:{'--qy-primary':'#224488'}};const before=readFileSync(resolve(root,'ui.theme.json'),'utf8');assert.equal(updateTheme(root,changed,envelope(root)).applied,false);assert.equal(readFileSync(resolve(root,'ui.theme.json'),'utf8'),before);const expected=envelope(root);put('ui.theme.json',{...theme,brand:'edited'});assert.throws(()=>updateTheme(root,changed,{...expected,apply:true}),/changed/);assert.equal(getTheme(root).theme.brand,'edited');updateTheme(root,changed,{...envelope(root),apply:true});assert.equal(getTheme(root).generatedMatches,true);assert.equal(updateTheme(root,changed,envelope(root)).diff.length,0);});
test('invalid existing theme is diagnostic FAIL and does not crash get',t=>{const {root,put}=fixture(t);put('ui.theme.json',{schemaVersion:1,brand:'azure',common:{},dark:{},compact:{}});const result=getTheme(root);assert.equal(result.status,'FAIL');assert.equal(result.generatedMatches,false);assert.match(result.validation.errors.join(','),/light/);});
for(const first of [true,false])test(`generated write failure rolls back ${first?'new':'existing'} source`,t=>{const {root,put,config}=fixture(t);if(first)rmSync(resolve(root,'ui.theme.json'));const sourceBefore=existsSync(resolve(root,'ui.theme.json'))?readFileSync(resolve(root,'ui.theme.json'),'utf8'):null;put('blocked','a regular file');config.theme.generated='blocked/theme.css';put('ui.config.json',config);assert.throws(()=>updateTheme(root,{...theme,brand:'candidate'},{...envelope(root),apply:true}),/EEXIST|ENOTDIR/);assert.equal(existsSync(resolve(root,'ui.theme.json')),!first);if(!first)assert.equal(readFileSync(resolve(root,'ui.theme.json'),'utf8'),sourceBefore);});
test('unknown generated CSS and third-party legacy rules are preserved',t=>{const {root,put,config}=fixture(t);put('ui.theme.generated.css','/* handwritten */ .third-party {color:red;}');assert.throws(()=>updateTheme(root,theme,{...envelope(root),apply:true}),/handwritten/);config.theme.legacyCss=['legacy.css'];put('ui.config.json',config);put('legacy.css','html[data-brand="old"] { --qy-primary:#456; } .map { color:#123; --vendor:3; } @media(min-width:800px){html[data-brand="old"]{--qy-primary:#789;}}');const report=getTheme(root);assert.equal(report.legacy[0].recognized.length,1);assert.ok(report.legacy[0].unmanaged.length>=3);assert.equal(report.legacy[0].migrationCandidates[0].light!==undefined,true);assert.match(readFileSync(resolve(root,'legacy.css'),'utf8'),/\.map/);});
test('AST allows aliases, legal reexports, native semantics, structure and data',t=>{const {root}=fixture(t);const result=checkProject(root);assert.equal(result.status,'UNVERIFIED');assert.equal(result.checks.syntax,'PASS');assert.equal(result.checks.imports,'PASS');assert.equal(result.checks.publicControlBypass,'UNVERIFIED');assert.equal(result.checks.deprecatedTokens,'N/A');assert.equal(result.checks.browser,'NOT_RUN');assert.equal(result.diagnostics.length,0);});
test('AST catches arbitrary hex/RGB/OKLCH, CSS paint and undefined tokens; dynamic stays unknown',t=>{const {root,put}=fixture(t);put('src/app.tsx','import {Button} from "@qingye_lab/ui"; const runtime = getRuntimeClass(); export const App=()=> <main><Button className="bg-[#191919] text-[rgb(25,25,25)] border-[oklch(0.4_0.2_30)] gap-(--qy-absent)"/><div className={runtime} style={{fontSize:18}}/><button aria-label="Native structural button"/></main>;');put('src/paint.css','.card {color: rgb(2,3,4); border-radius:8px}');const result=checkProject(root);assert.equal(result.exitCode,0);assert.equal(result.status,'FAIL');assert.ok(result.diagnostics.filter(d=>d.rule==='visual/hardcoded').length>=5);assert.ok(result.diagnostics.some(d=>d.status==='UNVERIFIED'));assert.ok(result.diagnostics.some(d=>d.rule==='token/undefined'));assert.equal(checkProject(root,{mode:'gate'}).exitCode,1);});
test('central token definitions and explicit third-party adapter scope are allowed',t=>{const {root,put,config}=fixture(t);config.tokenSources=['src/project-tokens.css'];config.adapters=['src/vendor'];put('ui.config.json',config);put('src/project-tokens.css',':root {--qy-project-mark:#123; color:#123;}');put('src/vendor/map.tsx','export const Map=()=> <div className="bg-[#123456] text-[20px]"/>;');put('src/app.tsx','export const App=()=> <div className="bg-(--qy-project-mark) grid gap-2"/>;');assert.equal(checkProject(root).newFailures,0);assert.equal(checkProject(root).checks.visual,'PASS');});
test('invalid exports and brand/brightness reuse are certain failures',t=>{const {root,put}=fixture(t);put('src/app.tsx','import {NoSuchExport} from "@qingye_lab/ui"; export {NoSuchExport as Foo} from "@qingye_lab/ui"; export const App=()=> <main data-theme="brand"/>;');const result=checkProject(root);assert.ok(result.diagnostics.some(d=>d.rule==='imports/invalid-export'));assert.ok(result.diagnostics.some(d=>d.rule==='theme/axes'));});
test('baseline is exact, exceptions separate, new issues never grow the baseline',t=>{const {root,put,config}=fixture(t);put('src/app.tsx','export const App=()=> <div className="bg-[#123456]"/>;');const first=checkProject(root),old=first.diagnostics[0];config.diagnostics.baseline='baseline.json';put('baseline.json',{schemaVersion:1,issues:[{id:old.id,reason:'Existing issue'}]});put('ui.config.json',config);const baselineBefore=readFileSync(resolve(root,'baseline.json'),'utf8');assert.equal(checkProject(root,{mode:'gate'}).exitCode,0);put('src/extra.tsx','export const Extra=()=> <div className="text-[rgb(1,2,3)]"/>;');const next=checkProject(root,{mode:'gate'});assert.equal(next.exitCode,1);assert.equal(next.newFailures,1);assert.equal(readFileSync(resolve(root,'baseline.json'),'utf8'),baselineBefore);const extra=next.diagnostics.find(d=>!d.disposition);config.diagnostics.exceptions='exceptions.json';put('exceptions.json',{schemaVersion:1,exceptions:[{rule:extra.rule,file:extra.file,line:extra.line,evidence:extra.evidence,reason:'approved adapter pending migration',reviewAfter:'2099-01-01'}]});put('ui.config.json',config);assert.equal(checkProject(root,{mode:'gate'}).exitCode,0);assert.equal(checkProject(root).diagnostics.find(d=>d.id===extra.id).disposition,'exception');});
test('syntax/missing scan failures are execution faults even in report mode',t=>{const {root,put,config}=fixture(t);put('src/broken.css','a { color:');assert.throws(()=>checkProject(root),/CSS scanner failed/);rmSync(resolve(root,'src/broken.css'));config.scan=['missing'];put('ui.config.json',config);assert.throws(()=>checkProject(root),/scan path missing/);});
test('init is dry-run, creates only its whitelist, is idempotent and detects conflicts before writing',t=>{const {root,put}=fixture(t,{configured:false});const plan=initProject(root);assert.equal(plan.applied,false);assert.equal(existsSync(resolve(root,'ui.config.json')),false);assert.equal(plan.status,'FAIL');assert.throws(()=>initProject(root,{apply:true}),/conflicts/);rmSync(resolve(root,'src/ui.ts'));rmSync(resolve(root,'src/ui.css'));initProject(root,{apply:true});assert.equal(initProject(root).changes.every(c=>c.status==='unchanged'),true);put('src/ui.css','handwritten');assert.throws(()=>initProject(root,{apply:true}),/conflicts/);assert.equal(readFileSync(resolve(root,'src/ui.css'),'utf8'),'handwritten');});
test('saved reports invalidate a newly added violation without rescanning or rewriting evidence',t=>{
  const {root,put,config}=fixture(t);
  assert.equal(readReports([root]).projects[0].status,'NOT_RUN');
  config.diagnostics.baseline='baseline.json';put('baseline.json',{schemaVersion:1,issues:[]});put('ui.config.json',config);
  const saved=checkProject(root,{save:true}),reportBefore=readFileSync(resolve(root,'.qingye/report.json'),'utf8'),baselineBefore=readFileSync(resolve(root,'baseline.json'),'utf8');
  assert.equal(saved.newFailures,0);assert.equal(readReports([root]).projects[0].stale,false);
  put('src/new.tsx','export const New=()=> <div className="bg-[#123456]"/>;');
  const summary=readReports([root]);assert.equal(summary.projects.length,1);assert.equal(summary.projects[0].project,saved.project);
  assert.equal(summary.projects[0].stale,true);assert.equal(summary.projects[0].status,'UNVERIFIED');
  assert.equal(summary.projects[0].generatedAt,saved.generatedAt);assert.deepEqual(summary.projects[0].counts,saved.counts);assert.equal(summary.projects[0].newFailures,0);
  assert.equal(readFileSync(resolve(root,'.qingye/report.json'),'utf8'),reportBefore);assert.equal(readFileSync(resolve(root,'baseline.json'),'utf8'),baselineBefore);
  const current=checkProject(root);assert.equal(current.newFailures,1);assert.ok(current.diagnostics.some(d=>d.file==='src/new.tsx'&&d.rule==='visual/hardcoded'&&d.status==='FAIL'));
});
test('saved reports invalidate removed and renamed scanned files',t=>{
  const {root}=fixture(t);checkProject(root,{save:true});
  renameSync(resolve(root,'src/app.tsx'),resolve(root,'src/renamed.tsx'));assert.equal(readReports([root]).projects[0].stale,true);
  renameSync(resolve(root,'src/renamed.tsx'),resolve(root,'src/app.tsx'));assert.equal(readReports([root]).projects[0].stale,false);
  rmSync(resolve(root,'src/app.tsx'));assert.equal(readReports([root]).projects[0].stale,true);
});
test('saved report freshness shares every scanner source extension and excludes ignored or unrelated files',t=>{
  const {root,put}=fixture(t);checkProject(root,{save:true});
  for(const name of ['outside/new.tsx','src/readme.md','src/data.json','src/node_modules/ignored.tsx','src/.git/ignored.tsx','src/dist/ignored.tsx'])put(name,'Not valid source; excluded by the configured scanner');
  assert.equal(readReports([root]).projects[0].stale,false);
  for(const extension of ['ts','tsx','js','jsx','css']){
    const name=`src/new.${extension}`;put(name,extension==='css'?'.new {}':'export const value=1;');
    assert.equal(readReports([root]).projects[0].stale,true,extension);
    rmSync(resolve(root,name));assert.equal(readReports([root]).projects[0].stale,false,extension);
  }
});
test('saved report freshness respects explicit file scan roots and changes to configuration',t=>{
  const {root,put,config}=fixture(t);config.scan=['src/app.tsx'];put('ui.config.json',config);checkProject(root,{save:true});
  put('src/new.tsx','export const New=()=> <div className="bg-[#123456]"/>;');put('src/ui.css','.outside {color:#123456}');
  assert.equal(readReports([root]).projects[0].stale,false);
  config.scan=['src'];put('ui.config.json',config);assert.equal(readReports([root]).projects[0].stale,true);
});
test('saved reports become stale on content and installed version changes',t=>{
  const {root,put}=fixture(t);checkProject(root,{save:true});put('src/ui.css','.x {}');assert.equal(readReports([root]).projects[0].stale,true);
  put('src/ui.css','');assert.equal(readReports([root]).projects[0].stale,false);
  const installed=JSON.parse(readFileSync(resolve(root,'node_modules/@qingye_lab/ui/package.json'),'utf8')),catalog=JSON.parse(readFileSync(resolve(root,'node_modules/@qingye_lab/ui/catalog.json'),'utf8'));
  installed.version='0.3.3';catalog.version='0.3.3';put('node_modules/@qingye_lab/ui/package.json',installed);put('node_modules/@qingye_lab/ui/catalog.json',catalog);
  assert.equal(readReports([root]).projects[0].stale,true);
});
test('saved report enumeration failures stay NOT_RUN instead of fresh',t=>{
  const {root}=fixture(t);checkProject(root,{save:true});const reportBefore=readFileSync(resolve(root,'.qingye/report.json'),'utf8');
  symlinkSync(resolve(root,'src/app.tsx'),resolve(root,'src/linked.tsx'));
  const summary=readReports([root]).projects[0];assert.equal(summary.status,'NOT_RUN');assert.notEqual(summary.stale,false);assert.match(summary.error,/Scanner does not follow symlink/);
  assert.equal(readFileSync(resolve(root,'.qingye/report.json'),'utf8'),reportBefore);
  rmSync(resolve(root,'src/linked.tsx'));rmSync(resolve(root,'src'),{recursive:true});
  const missing=readReports([root]).projects[0];assert.equal(missing.status,'NOT_RUN');assert.notEqual(missing.stale,false);assert.match(missing.error,/Configured scan path missing/);
});
test('impact reads existing ledger and invalidates stale observations instead of no-effect claims',t=>{const {root,put,config}=fixture(t);config.ledger='token-ledger.json';config.ledgerRoot='.';put('ui.config.json',config);put('token-ledger.json',{generatedAt:'2026-10-01',static:{fingerprint:{sha256:'abc',inputs:[{path:'src/ui.css',sha256:'stale'}]},records:[{token:'--qy-primary',part:'button',selector:'[data-slot=button]',sourceComponent:'button'}]},runtime:{fingerprint:'abc'},computation:{cases:[{token:'--qy-primary',part:'button',status:'PASS'}]}});const result=getImpact(root,'--qy-primary');assert.equal(result.runtimeFresh,false);assert.equal(result.observations[0].status,'NOT_RUN');assert.equal(getImpact(root,'--qy-never-measured').status,'UNVERIFIED');});
test('CLI report/gate/config failure codes are 0/1/2 and writes require a reviewed envelope',t=>{const {root,put}=fixture(t),bin=fileURLToPath(new URL('../bin/qingye-ui.mjs',import.meta.url));put('src/issue.tsx','export const Issue=()=> <div className="bg-[#123456]"/>;');const run=args=>spawnSync(process.execPath,[bin,...args],{encoding:'utf8'});assert.equal(run(['check','--project',root,'--json']).status,0);assert.equal(run(['check','--project',root,'--mode','gate','--json']).status,1);assert.equal(run(['info','--project',root+'/missing']).status,2);put('candidate.json',theme);assert.equal(run(['theme','update','--project',root,'--input',root+'/candidate.json','--apply']).status,2);assert.equal(run(['theme','update','--project',root,'--input',root+'/candidate.json']).status,0);});
test('info without config still returns actual installed facts and never initializes',t=>{const {root}=fixture(t,{configured:false});const result=projectInfo(root);assert.equal(result.version,'0.3.2');assert.equal(result.missingConfig,'ui.config.json');assert.equal(result.status,'UNVERIFIED');assert.equal(existsSync(resolve(root,'ui.config.json')),false);});
test('private package subpaths are FAIL even when TypeScript cannot resolve them',t=>{const {root,put}=fixture(t);put('src/app.tsx','import {Button} from "@qingye_lab/ui/src/components/button"; export const App=()=> <Button/>;');const result=checkProject(root);assert.ok(result.diagnostics.some(d=>d.rule==='imports/private'&&d.status==='FAIL'));assert.equal(result.exitCode,0);assert.equal(checkProject(root,{mode:'gate'}).exitCode,1);});
test('only actually used optional-peer components require their own installed peers',t=>{
  const {root,put}=fixture(t);const catalog=JSON.parse(readFileSync(resolve(root,'node_modules/@qingye_lab/ui/catalog.json'),'utf8'));catalog.components[0].dependencies={optionalPeers:[]};catalog.components.push({name:'chart',exports:['Chart'],dependencies:{optionalPeers:['recharts']}},{name:'data-table',exports:['DataTable'],dependencies:{optionalPeers:['@tanstack/react-table']}});put('node_modules/@qingye_lab/ui/catalog.json',catalog);put('node_modules/@qingye_lab/ui/index.d.ts','export declare const Button: (props:any)=>any; export declare const Chart:(props:any)=>any; export declare const DataTable:(props:any)=>any;');
  assert.equal(checkProject(root).executionFaults.length,0);
  put('src/app.tsx','import {Button,Chart} from "@qingye_lab/ui"; export const App=()=> <Button/>;');assert.equal(checkProject(root).executionFaults.length,0);
  put('src/app.tsx','import type {Chart} from "@qingye_lab/ui"; export type OnlyType=typeof Chart;');assert.equal(checkProject(root).executionFaults.length,0);
  put('src/app.tsx','import {Chart as Plot} from "@qingye_lab/ui"; export const App=()=> <Plot/>;');const chart=checkProject(root);assert.equal(chart.exitCode,2);assert.equal(chart.completed,false);assert.ok(chart.diagnostics.some(d=>d.rule==='imports/missing-peer'&&d.evidence.includes('recharts')));assert.equal(chart.executionFaults.includes('@tanstack/react-table'),false);
  put('src/ui.ts','export {Chart as ProjectChart} from "@qingye_lab/ui";');put('src/app.tsx','import {ProjectChart} from "@local/ui"; export const App=()=> <ProjectChart/>;');assert.equal(checkProject(root).executionFaults.includes('recharts'),true);
  put('src/app.tsx','import * as UI from "@qingye_lab/ui"; export const App=()=> <UI.DataTable/>;');assert.equal(checkProject(root).executionFaults.includes('@tanstack/react-table'),true);
  put('node_modules/@tanstack/react-table/package.json',{name:'@tanstack/react-table',main:'index.js'});put('node_modules/@tanstack/react-table/index.js','module.exports={};');assert.equal(checkProject(root).executionFaults.length,0);
});
test('presets change severity/gate policy, not facts; report/gate stay independent',t=>{
  const {root,put,config}=fixture(t);put('src/app.tsx','export const App=()=> <div className="bg-[#123456]"/>;');config.diagnostics.preset='recommended';put('ui.config.json',config);const recommended=checkProject(root,{mode:'gate'});assert.equal(recommended.status,'FAIL');assert.equal(recommended.diagnostics[0].severity,'warning');assert.equal(recommended.exitCode,0);
  config.diagnostics.preset='personal';put('ui.config.json',config);assert.equal(checkProject(root,{mode:'gate'}).exitCode,1);assert.equal(checkProject(root,{mode:'report'}).exitCode,0);
  config.diagnostics.preset='legacy';put('ui.config.json',config);const legacy=checkProject(root,{mode:'gate'});assert.equal(legacy.exitCode,1);assert.equal(legacy.legacyBaseline,'NOT_CONFIGURED');config.diagnostics.baseline='baseline.json';put('baseline.json',{schemaVersion:1,issues:[{id:legacy.diagnostics[0].id,reason:'Exact existing issue'}]});put('ui.config.json',config);assert.equal(checkProject(root,{mode:'gate'}).exitCode,0);const before=readFileSync(resolve(root,'baseline.json'),'utf8');put('src/new.tsx','export const New=()=> <div className="text-[rgb(1,2,3)]"/>;');assert.equal(checkProject(root,{mode:'gate'}).exitCode,1);assert.equal(readFileSync(resolve(root,'baseline.json'),'utf8'),before);
});
test('CLI preserves a null expected source fingerprint instead of trusting a new outside creation',t=>{
  const {root,put}=fixture(t),bin=fileURLToPath(new URL('../bin/qingye-ui.mjs',import.meta.url));rmSync(resolve(root,'ui.theme.json'));const expected=envelope(root);assert.equal(expected.fingerprint,null);put('candidate-envelope.json',{theme,...expected});put('ui.theme.json',{...theme,brand:'external'});const before=readFileSync(resolve(root,'ui.theme.json'),'utf8');const result=spawnSync(process.execPath,[bin,'theme','update','--project',root,'--input',resolve(root,'candidate-envelope.json'),'--apply'],{encoding:'utf8'});assert.equal(result.status,2);assert.match(result.stderr,/SOURCE_CONFLICT/);assert.equal(readFileSync(resolve(root,'ui.theme.json'),'utf8'),before);
});

test('CLI accepts a CSS custom property as the token argument and rejects a missing value',t=>{const {root}=fixture(t),bin=fileURLToPath(new URL('../bin/qingye-ui.mjs',import.meta.url));const run=args=>spawnSync(process.execPath,[bin,'impact','--project',root,...args],{encoding:'utf8'});const result=run(['--token','--qy-primary','--json']);assert.equal(result.status,0);assert.equal(JSON.parse(result.stdout).status,'NOT_RUN');const missing=run(['--token','--json']);assert.equal(missing.status,2);assert.equal(JSON.parse(missing.stderr).code,'INVALID_ARGUMENT');});
