import type { ComponentMeta } from "@/lib/types";
export default {
  title: "单段展开 Collapsible", titleEn: "Collapsible", description: "主动展开同一对象的补充内容。", descriptionEn: "Reveal additional content for the same object.",
  category: "布局", layer: "primitive", source: "local", exports: ["Collapsible", "CollapsibleTrigger", "CollapsiblePanel", "CollapsiblePrimitive"], keywords: ["collapsible", "disclosure", "展开", "折叠"],
  decisions: "触发名称与单段内容关联；默认保留输入，关闭只结束呈现。", decisionsEn: "Relate the named trigger to one content region. Retain input by default; closing only ends its presentation.",
  api: [{ name: "Collapsible", description: "单段内容的展开状态。", descriptionEn: "Expansion state for one section.", props: [{ name: "open / defaultOpen / onOpenChange", type: "CollapsiblePrimitive.Root.Props", description: "真实展开状态与可取消变更请求。", descriptionEn: "Actual open state and cancelable change requests." }, { name: "disabled", type: "boolean", description: "禁用切换。", descriptionEn: "Disable toggling." }] }, { name: "CollapsibleTrigger", description: "默认 Button quiet，支持原语 render/ref/事件。", descriptionEn: "Defaults to quiet Button; supports primitive render, refs, and events." }, { name: "CollapsiblePanel", description: "关联内容与保持策略。", descriptionEn: "Associated content and retention policy.", props: [{ name: "keepMounted", type: "boolean", default: "true", description: "保留关闭内容和原生字段；应用决定隐藏字段是否禁用。", descriptionEn: "Retain closed content and native fields; the application decides whether hidden fields are disabled." }, { name: "render / ref / className / style", type: "CollapsiblePrimitive.Panel.Props", description: "透传呈现及原语状态。", descriptionEn: "Forward presentation and primitive states." }] }],
  keyboard: [{ keys: "Enter / Space", description: "展开或收起。", descriptionEn: "Expand or collapse." }, { keys: "Tab / Shift+Tab", description: "访问触发者与展开内容。", descriptionEn: "Reach the trigger and expanded content." }], notes: ["多项同组展开使用 Accordion。", "关闭不声明取消、撤销或保存。"], notesEn: ["Use Accordion for a group of expandable sections.","Closing establishes no cancellation, undo, or save result."],
  design: { methods: ["展开有据", "进退相承"], whenToUse: ["同一对象有可主动展开的补充内容。"], avoid: ["把必要后果只放在默认隐藏内容。"], composition: ["Trigger 与 Panel 保留公共原语关联。"], stateOwner: { library: ["open、键盘和 ARIA。"], application: ["内容、输入和业务状态。"] }, responsive: ["内容换行且自然增长。"], customization: ["field gap、Button 和 motion.css 共享角色。"] }, designEn: {"whenToUse":["One object has supplementary content to disclose deliberately."],"avoid":["Putting necessary consequences solely in initially hidden content."],"composition":["Trigger and Panel retain public primitive associations."],"stateOwner":{"library":["Open state, keyboard, and ARIA."],"application":["Content, inputs, and business states."]},"responsive":["Content wraps and grows naturally."],"customization":["Shared field gap, Button, and motion.css roles."]},
} satisfies ComponentMeta;
