import type { ComponentMeta } from "@/lib/types";

export default {
  title: "滑块 Slider", titleEn: "Slider",
  description: "在明确区间内输入数值或有序范围。", descriptionEn: "Enter a number or an ordered range within explicit bounds.",
  category: "表单", layer: "primitive", source: "local", exports: ["Slider", "SliderControl", "SliderTrack", "SliderIndicator", "SliderThumb", "SliderLabel", "SliderValue", "SliderPrimitive"],
  api: [
    { name: "Slider", description: "数值与范围状态，公开各部位供组合。", descriptionEn: "Value and range state with public parts for composition.", props: [
      { name: "value / defaultValue", type: "number | readonly number[]", description: "受控值或非受控初值；未传时从 min 开始。数组每项对应一个带 index 的 Thumb。", descriptionEn: "Controlled or uncontrolled initial value; omission starts at min. Each array entry corresponds to an indexed Thumb." },
      { name: "min / max / step / largeStep", type: "number", default: "0 / 100 / 1 / 10", description: "有限 min<max，正步进；min 是步进原点，max 必须落在步进上。越界、非有限或未对齐的显式值抛 RangeError，不静默纠正。", descriptionEn: "Finite min<max and positive steps; min is the origin and max must align. Explicit out-of-range, nonfinite, or misaligned values throw RangeError without silent correction." },
      { name: "minStepsBetweenValues / thumbCollisionBehavior", type: 'number / "push" | "swap" | "none"', default: '0 / "push"', description: "有序范围的最小间距和指针碰撞策略；显式数组必须满足间距。", descriptionEn: "Minimum separation and pointer collision strategy for an ordered range; explicit arrays must satisfy spacing." },
      { name: "onValueChange / onValueCommitted", type: "(value, details) => void", description: "即时值与本次操作提交；details.reason 对应 keyboard/drag/track-press/input-change，可取消变化。提交不等于持久化成功。", descriptionEn: "Immediate changes and the current interaction's commit. details.reason identifies keyboard/drag/track-press/input-change; changes are cancelable. Commit does not establish successful persistence." },
      { name: "disabled / readOnly", type: "boolean", default: "false", description: "禁用不提交表单；只读保留名称、焦点、值和提交，取消所有原语变化。", descriptionEn: "Disabled excludes form submission. Read-only retains names, focus, values, and submission while canceling primitive changes." },
      { name: "name / form", type: "string", description: "表单名与外部 form；多个 Thumb 以同名字段重复序列化。", descriptionEn: "Form name and external form; multiple Thumbs serialize repeated fields under the same name." },
      { name: "orientation / thumbAlignment", type: '"horizontal" | "vertical" / Base UI alignment', default: '"horizontal" / "edge"', description: "工作高度跟随填值控件的一套几何；抓手跟随标签文字，密度不改它。edge 让端点位于工作范围内。", descriptionEn: "The working height follows the one fill-control geometry; the thumb follows its label text and is untouched by density. edge keeps endpoints within the workspace." },
      { name: "format / locale / render / ref / className / style", type: "Base UI props", description: "数值格式、语言、根部位和原语状态样式；主题轴独立。", descriptionEn: "Number formatting, locale, root composition, and primitive state styles; theme axes remain independent." },
    ] },
    { name: "SliderControl / SliderTrack / SliderIndicator", description: "交互工作区、完整范围与实际输入区间。", descriptionEn: "Interactive workspace, complete range, and actual input interval.", props: [{ name: "render / ref / className / style", type: "Base UI composition", description: "各部位透传 ARIA、data 与原生事件；轨道厚度读 slider-track-size，纵向工作长度读 slider-vertical-length。", descriptionEn: "Parts forward ARIA, data, and native events. Track thickness reads slider-track-size and vertical extent reads slider-vertical-length." }] },
    { name: "SliderThumb", description: "可拖动部位，包含真实 range input。", descriptionEn: "Draggable part containing an actual range input.", props: [{ name: "index / aria-label / getAriaLabel", type: "number / string / (index) => string", description: "区间每个 Thumb 指定 index，并给出能区分上下限的名称。", descriptionEn: "Specify each range Thumb's index and a name distinguishing its lower/upper meaning." }, { name: "getAriaValueText / aria-valuetext / inputRef", type: "Base UI props", description: "默认读屏值是格式化数值，不添加英语上下限文案。可传单位与读屏值；inputRef、onKeyDown/onFocus/onBlur 对应真实 input。", descriptionEn: "The default accessible value is a formatted number without added English bound labels. Supply units/value text as needed; inputRef and onKeyDown/onFocus/onBlur target the actual input." }, { name: "disabled / render / ref / className / style", type: "Base UI composition", description: "单项禁用与公开部位组合；readOnly 和 Field invalid 接到真实 input 的 ARIA。", descriptionEn: "Per-item disabling and public composition; readOnly and Field invalid reach actual input ARIA." }] },
    { name: "SliderLabel / SliderValue", description: "关联所有 Thumb 的名称与实际数值 output。Value 的 children 接收 formattedValues/values。", descriptionEn: "Names associated with all Thumbs and actual numeric output. Value children receives formattedValues/values." },
    { name: "SliderPrimitive", description: "Base UI Slider 原语命名空间。", descriptionEn: "Base UI Slider primitive namespace." },
  ],
  keyboard: [{ keys: "Tab / Shift+Tab", description: "依次到达可用滑块。", descriptionEn: "Reach available thumbs in sequence." }, { keys: "方向键", keysEn: "Arrow keys", description: "按 step 改值；方向与 orientation/RTL 一致。", descriptionEn: "Change by step, respecting orientation/RTL." }, { keys: "Home / End", description: "到达允许的起止端点。", descriptionEn: "Reach permitted starting/ending bounds." }, { keys: "PageUp / PageDown / Shift+方向键", keysEn: "PageUp / PageDown / Shift+Arrow keys", description: "按 largeStep 改值，受区间与相邻值约束。", descriptionEn: "Change by largeStep within range and neighboring-value constraints." }],
  notes: ["必须给 SliderLabel 或每个 Thumb 的名称，多滑块名称需要区分。", "原语交互按步进吸附；显式无效值会抛 RangeError。", "4px 轨道厚度和 10rem 纵向长度是集中预设，修改 tokens/components.css 或项目主题；浏览器对比与几何仍需验收。"], notesEn: ["Provide SliderLabel or a name for each Thumb; multiple-thumb names must differ.","Primitive interaction snaps to steps; explicit invalid values throw RangeError.","4px track thickness and 10rem vertical length are central presets, adjustable in tokens/components.css or project themes. Actual browser contrast/geometry still require acceptance."],
  decisions: "Slider 输入真实数值。进度使用 Progress，测量结果使用 Meter；onValueCommitted 只表示当前交互提交。", decisionsEn: "Slider inputs actual numeric values. Use Progress for progress and Meter for measurements; onValueCommitted indicates only the current interaction's commit.",
  design: {
    methods: ["名实相符", "相成相制", "进退相承"], whenToUse: ["有明确有限范围与步进的数值", "需要拖动调整的数值区间"], avoid: ["精确键入使用 NumberField", "进度或未知任务状态不用 Slider"],
    composition: ["Label/Value + Control → Track → Indicator/Thumb；FieldDescription/FieldError 继续关联同一输入"], stateOwner: { library: ["拖动、焦点、键盘、非受控值"], application: ["受控值、区间与步进、invalid、持久化"] },
    responsive: ["控制高跟随密度轴，抓手跟随标签文字；窄屏增量照旧，触摸与真实拖动未在本子任务浏览器验收"], customization: ["具名轨道厚度与纵向长度预设，项目可覆写；Thumb 边框聚焦只变色"],
  }, designEn: {"whenToUse":["Numeric values with explicit finite ranges and steps.","Numeric intervals needing drag adjustment."],"avoid":["Use NumberField for precise typing.","Do not use Slider for progress or unknown task states."],"composition":["Label/Value + Control → Track → Indicator/Thumb; FieldDescription/FieldError continue referring to the same input."],"stateOwner":{"library":["Dragging, focus, keyboard, and uncontrolled values."],"application":["Controlled values, ranges/steps, invalid facts, and persistence."]},"responsive":["Control/thumb profiles retain five narrow-screen increments; this subtask did not browser-accept touch or actual dragging."],"customization":["Named track-thickness/vertical-length presets are project-overridable; Thumb focus changes border color only."]},
} satisfies ComponentMeta;
