import type { ComponentMeta } from "@/lib/types";
export default {
  title: "边缘工作面 Drawer", titleEn: "Drawer", description: "从边缘进入工作面，再返回入口。", descriptionEn: "Enter an edge-aligned work surface and return to its entry point.", category: "浮层", layer: "primitive", source: "local",
  exports: ["Drawer", "DrawerTrigger", "DrawerPopup", "DrawerTitle", "DrawerDescription", "DrawerContent", "DrawerClose", "DrawerCreateHandle", "DrawerPrimitive"], keywords: ["drawer", "sheet", "边缘", "抽屉"],
  decisions: "方向由公开 swipeDirection 决定；实际 modal 决定焦点与背景阻断，关闭不代表撤销。", decisionsEn: "Public swipeDirection controls the edge. Actual modality controls focus and background blocking; closing does not imply undo.",
  api: [{ name: "Drawer", description: "真实开关、方向与阻断方式。", descriptionEn: "Actual open state, direction, and blocking mode.", props: [{ name: "open / defaultOpen / onOpenChange", type: "DrawerPrimitive.Root.Props", description: "实际开关与可取消请求；调用方事件先执行，受控拒绝不提升层级。", descriptionEn: "Actual opening and cancelable requests; caller events run first and controlled refusal does not promote layers." }, { name: "modal", type: 'boolean | "trap-focus"', default: "true", description: "完整阻断、非阻断或只困住焦点；只有完整阻断显示遮罩并声明 aria-modal。", descriptionEn: "Full blocking, nonblocking, or focus trapping only. Only full blocking shows a backdrop and declares aria-modal." }, { name: "swipeDirection", type: '"down" | "up" | "left" | "right"', default: '"down"', description: "退出方向与所在边缘，沿用原语手势、snapPoints 与 activeSnapPoint 公共 API。", descriptionEn: "Exit direction and owning edge; retains public primitive gestures, snapPoints, and activeSnapPoint." }] }, { name: "DrawerPopup", description: "边缘工作面、遮罩与视口组合。", descriptionEn: "A composition of edge workspace, backdrop, and viewport.", props: [{ name: "initialFocus / finalFocus", type: "DialogFocusTarget", default: "true", description: "默认首个控件与触发者；可指定有意义的可聚焦目标，不接受 false。", descriptionEn: "Defaults to the first control and trigger; callers may name meaningful focusable targets. false is not accepted." }, { name: "portalProps / backdropProps / viewportProps", type: "DrawerPrimitive 部位 Props", typeEn: "DrawerPrimitive part props", description: "原生 Portal、render/ref/事件与样式透传；调用方 style 后合并，可覆盖默认层级。", descriptionEn: "Forwards native Portal, render, refs, events, and styles. Caller style merges last and can override default layers." }] }, { name: "DrawerTitle / DrawerDescription / DrawerContent", description: "真实名称、必要说明和可滚动工作内容，不造业务状态。", descriptionEn: "Actual names, necessary descriptions, and scrollable working content without invented business states." }, { name: "DrawerTrigger / DrawerClose", description: "复用 Button；Close 无 children 时读取 locale.close。", descriptionEn: "Use Button; Close reads locale.close when children are omitted." }],
  keyboard: [{ keys: "Enter / Space", description: "从入口展开。", descriptionEn: "Open from the trigger." }, { keys: "Tab / Shift+Tab", description: "按实际 modal 设置在工作面中导航。", descriptionEn: "Navigate the workspace according to its actual modal setting." }, { keys: "Esc", description: "关闭当前层，再返回该层入口。", descriptionEn: "Close the current layer and return to its entry." }],
  notes: ["程序打开且无触发者时明确 finalFocus。", "草稿、保存、放弃与撤销由应用分别处理。", "Popup 自然容量受视口限制；长内容滚动，左右边缘没有任意固定宽度。", "共享 FloatingLayerScope/useFloatingLayer 为所属候选与嵌套工作面排序；调用方覆盖 zIndex 可破坏该关系。", "ARIA实测驱动的契约收窄：Portal固定keepMounted=false，JS传true也不保留关闭DOM。应用显式持有草稿；Primitive自行组合仍有原语保留Portal隔离缺陷。"], notesEn: ["Specify finalFocus when opening programmatically without a trigger.","Applications handle drafts, saving, abandonment, and undo separately.","Popup capacity is viewport constrained. Long content scrolls; left/right edges have no arbitrary fixed width.","Shared FloatingLayerScope/useFloatingLayer order associated candidates and nested workspaces. Overriding zIndex can break this relationship.","The contract was narrowed after actual ARIA checks: Portal fixes keepMounted=false even for JavaScript callers passing true. Applications explicitly retain drafts; custom Primitive composition still exposes the primitive's retained-Portal isolation defect."],
  design: { methods: ["名实相符", "展开有据", "进退相承"], whenToUse: ["任务需要边缘工作面且保留真实退出入口。"], avoid: ["用抽出方向冒充不同阻断语义。"], composition: ["Title/Description/Content 与既有 Button/Input/Popover 组合。"], stateOwner: { library: ["实际 open、原语手势、焦点、背景阻断和共享层级。"], application: ["输入、草稿与结果。"] }, responsive: ["内容容量受视口限制；本批手势和桌面真实几何由浏览器 owner 验证。"], customization: ["共享面、线、padding、圆角与 motion.css；无独立尺寸变体。"] }, designEn: {"whenToUse":["A task requires an edge workspace with an actual exit."],"avoid":["Treating slide direction as a different blocking semantic."],"composition":["Title/Description/Content with existing Button/Input/Popover."],"stateOwner":{"library":["Actual open state, primitive gestures, focus, background blocking, and shared layers."],"application":["Inputs, drafts, and outcomes."]},"responsive":["Content capacity is viewport constrained; the browser owner verifies this batch's gestures and actual desktop geometry."],"customization":["Shared surfaces, lines, padding, radii, and motion.css; no independent size variant."]},
} satisfies ComponentMeta;
