import type { ComponentMeta } from "@/lib/types";
export default {
  title: "两量关系 ScatterChart", titleEn: "ScatterChart", description: "两个数值量之间的关系；全比较形式，1 至 3 个系列，同源的散点图、命名的双轴与按需展开的数据表。", descriptionEn: "The relationship between two numeric quantities; an all-pairs form with one to three series, a same-source scatter plot, named axes and an on-demand data table.", category: "数据展示", layer: "pattern", source: "local", exports: ["ScatterChart"], keywords: ["scatter", "scatter plot", "relationship", "correlation", "散点", "散点图", "关系", "相关"],
  decisions: "x、y 都是数值轴——这是散点的任务定义，不是违反「永远一个数值轴」；该禁令禁止的是同一类别轴上叠两条不同量纲的 Y 轴制造虚假相关。全比较形式最多 3 个系列，超过应合并为「其他」或拆成多图。",
  decisionsEn: "Both x and y are value axes by the task's own definition, not a violation of \"always one value axis\" — that ban targets stacking two different-unit Y-axes on one shared category axis, which fabricates correlation. As an all-pairs form it accepts at most three series; more should fold into \"Other\" or split into separate charts.",
  api: [{ name: "ScatterChart", description: "figure 名称、命名的双轴、按系列着色的标记与同源可见 Table。", descriptionEn: "A named figure, named x/y axes, series-colored markers and a visible same-source Table.", props: [
    { name: "label", type: "string", description: "非空真实语义名称。", descriptionEn: "A nonempty semantic name for the actual data." },
    { name: "xLabel / yLabel", type: "string", description: "横轴与纵轴量的是什么，例如「记录数」「失败率」。", descriptionEn: "What the x and y axes measure, e.g. \"records\" and \"failure rate\"." },
    { name: "series", type: "readonly { key: string; label: string; points: readonly { id: string; label: string; x: number; y: number }[] }[]", description: "1 至 3 个系列。只有一个系列时取第一色、不显示图例；两个以上按 chart1..3 取色并配不同标记形状。每个点需要稳定 id 与非空名称。", descriptionEn: "One to three series. A single series takes the first color without a legend; two or more take the chart1..3 order with distinct marker shapes. Every point needs a stable id and a nonempty name." },
    { name: "formatX / formatY", type: "(value: number) => ReactNode", description: "格式化已知数值；默认按 UILocale 数值 Intl。", descriptionEn: "Format known values; defaults to Intl number formatting for UILocale." },
  ] }],
  notes: ["超过 3 个系列会抛出错误：全比较形式任意两点都可能相邻，色觉校验比相邻校验更严，更多系列应合并为「其他」或改用小图版面拆分。", "点的命中区≥24px，大于 8px 的可见标记，指针不必正中标记。", "x、y 轴域按实际数据范围加少量留白，不强制从零起——散点不是从基线生长的柱。", "悬停读数只增强，不替代按需展开的等价数据表。"],
  notesEn: ["More than three series throws: as an all-pairs form any two points may sit adjacent, so its color-vision check is stricter than an adjacent check; fold extra series into \"Other\" or split into small multiples.", "Each point's hit area is at least 24px, larger than its visible 8px marker; the pointer need not land dead-center.", "The x and y domains pad slightly around the actual data range rather than forcing a zero baseline — a scatter point does not grow from a baseline like a bar.", "Hover readouts only enhance; they never replace the on-demand equivalent data table."],
  design: { methods: ["名实相符", "墨分五色"], whenToUse: ["需要看两个数值量之间是否存在关系，例如记录数与失败率。"], avoid: ["只有一个数值要展示（用 Stat）；随时间的单一趋势（用 Chart line/area）；类别之间的比较（用 Chart bar）。"], composition: ["Recharts 公开原语 + 当前 Table；复用 Chart 的 Marker 标记与悬停外壳。没有可画的点时，调用方在原位改放 Empty。"], stateOwner: { library: ["同源投影、可见等价表、标记形态与基础名称。"], application: ["数据、量纲、真实性与状态文字。"] }, responsive: ["图高集中预设可覆写，表格原生滚动/换行。"], customization: ["chart1..3 语义色；不另造散点调色板。"] },
  designEn: { whenToUse: ["Checking whether two numeric quantities are related, e.g. record count and failure rate."], avoid: ["A single number to show (use Stat); a single trend over time (use Chart line/area); comparison between categories (use Chart bar)."], composition: ["Public Recharts primitives with the current Table; reuses Chart's Marker shapes and hover shell. With no point to plot, the caller renders Empty in place of the chart."], stateOwner: { library: ["Same-source projection, visible equivalent table, marker shapes and basic naming."], application: ["Data, units, truth and state content."] }, responsive: ["The centralized plot-height preset can be overridden; the table scrolls and wraps natively."], customization: ["chart1..3 semantic colors; no separate scatter palette."] },
} satisfies ComponentMeta;
