import type { ComponentMeta } from "@/lib/types";
export default {
  title: "顺序阅读 Carousel", titleEn: "Carousel", description: "手动访问有限内容，保留真实当前位置与前后边界。", descriptionEn: "Manually read finite content with an actual position and clear boundaries.", category: "数据展示", layer: "pattern", source: "local", exports: ["Carousel"], keywords: ["carousel", "slide", "轮播", "顺序阅读"],
  decisions: "位置不代表已经阅读或完成；默认不播放、不环回。只有当前项可达，所有项保持原生输入。", decisionsEn: "Position does not imply reading or completion. There is no autoplay or wraparound. Only the current item is reachable, while native inputs stay mounted.",
  api: [{ name: "Carousel", description: "有名称的阅读region、原生ScrollArea与Button前后入口。", descriptionEn: "A named reading region, native ScrollArea and previous/next Button controls.", props: [
    { name: "label", type: "string", description: "整个阅读对象的非空可访问名称。", descriptionEn: "A nonempty accessible name for the whole reading object." },
    { name: "items", type: "readonly { id: string; label: string; content: ReactNode }[]", description: "有限真实内容、唯一稳定id与非空项名称。", descriptionEn: "Finite real content, unique stable ids and nonempty item names." },
    { name: "value / defaultValue / onValueChange", type: "string / string / (id: string) => void", description: "当前项id与变更请求；受控值由调用方接受。非受控项移除后回到首个现存项。", descriptionEn: "Current item id and change requests. The caller accepts controlled values. Removing the uncontrolled current item selects the first remaining item." },
    { name: "emptyContent", type: "ReactNode", description: "没有项时的真实内容；不伪造当前位置或前后入口。", descriptionEn: "Actual empty content, without a fabricated position or navigation." },
    { name: "render / ref / style / className / 原生属性", nameEn: "render / ref / style / className / native props", type: "useRender.ComponentProps<section>", description: "公共组合、id、ARIA、事件与ref。", descriptionEn: "Public composition, id, ARIA, events and refs." },
  ] }], keyboard: [{ keys: "Enter / Space", description: "操作当前前后Button；首尾aria-disabled保持焦点且不改变位置。", descriptionEn: "Operate previous/next buttons. aria-disabled boundaries retain focus and do not change position." }, { keys: "ArrowLeft / ArrowRight / Home / End", description: "仅根自身获得焦点时切换；左右跟随实际direction，不截获输入字段键盘。", descriptionEn: "Switch only while the root itself has focus. Arrows follow actual direction and do not intercept field keys." }, { keys: "Tab / Shift+Tab", description: "访问当前项及前后控件，关闭项不可达。", descriptionEn: "Reach the current item and navigation controls. Hidden items remain unreachable." }],
  notes: ["没有自动播放或环回API。", "隐藏项保持字段；是否提交或禁用由应用原生字段属性决定。", "当前项移除或外部切换时只恢复仍属旧项的焦点，外部焦点不被夺回。", "受控value必须指向现存项，稳定id不能按当前索引替换。"],
  notesEn: ["There is no autoplay or wraparound API.", "Hidden items retain fields; application-owned native field attributes decide submission and disabling.", "Removing or externally changing the current item restores focus only when it still belongs to the old item. External focus is not reclaimed.", "Controlled value must identify a current item. Keep ids stable instead of replacing them with indexes."],
  designEn: { whenToUse: ["Finite content needs deliberate sequential access."], avoid: ["Autoplaying essential content or describing position as completion."], composition: ["Button and native ScrollArea; items retain actual content."], stateOwner: { library: ["Current presentation, boundaries and necessary focus recovery."], application: ["Content, inputs, business facts and controlled value."] }, responsive: ["Long names wrap; native scrolling handles content capacity."], customization: ["Shared panel/action gaps, text and internal focus; no new global geometry tokens."] },
  design: { methods: ["名实相符", "进退相承", "展开有据"], whenToUse: ["有限内容需主动按顺序访问。"], avoid: ["自动播放关键内容或把当前位置写成完成。"], composition: ["Button + 原生ScrollArea；items保存实际内容。"], stateOwner: { library: ["当前呈现、首尾与必要焦点恢复。"], application: ["内容、输入、业务事实与受控值。"] }, responsive: ["长名称换行；容量由原生滚动承接。"], customization: ["共享panel/action gap、文字与盒内焦点，不新增全局几何token。"] },
} satisfies ComponentMeta;
