import type { ComponentMeta } from "@/lib/types";
export default {
  title: "虚拟列表 VirtualList", titleEn: "Virtual list",
  description: "以稳定项身份呈现等高长集合的可达窗口。", descriptionEn: "An accessible window over a fixed-height collection with stable item identity.",
  category: "工具", layer: "primitive", source: "local", exports: ["VirtualList"],
  api: [{ name: "VirtualList<Item>", description: "集合渲染边界，真实 list/listitem，不提供选择或业务列。", descriptionEn: "Collection rendering boundary with actual list/listitem semantics, without selection or business columns.", props: [
    { name: "items / getKey / renderItem", type: "readonly Item[] / (item,index)=>React.Key / (item,index)=>ReactNode", description: "真实集合、稳定唯一 key 与内容；重复 key 显式报错。不得用不稳定位置冒充项身份。", descriptionEn: "Actual collection, stable unique keys, and content; duplicate keys throw. Unstable positions cannot impersonate identity." },
    { name: "itemSize / height", type: "number", description: "调用方提供等高项外高与视口高，CSS px；有限正数，0/无穷等显式报错。总高/偏移/窗口从关系计算。", descriptionEn: "Caller-supplied equal outer item height and viewport height in CSS px. Finite positive values; zero/infinity throw. Total height, offsets, and window derive from these relationships." },
    { name: "overscan", type: "number", default: "2", description: "窗口两侧的渲染预算预设，非负整数；不是视觉尺寸。", descriptionEn: "A nonnegative integer rendering-budget preset on both window edges, rather than a visual dimension." },
    { name: "render / ref / style / className / events / ARIA", type: "useRender.ComponentProps<'div'>", description: "真实滚动视口出口；height 由显式 height 参数承担，测量实际 clientHeight 适应视口变化。给集合可识别名称。", descriptionEn: "Actual viewport composition; explicit height owns its height, and measured clientHeight adapts to viewport changes. Give the collection an identifiable name." },
  ] }],
  keyboard: [{ keys: "Tab", description: "到达集合视口与已挂载的内部操作。", descriptionEn: "Reach the collection viewport and mounted internal actions." }, { keys: "方向 / Home / End", keysEn: "Arrow keys / Home / End", description: "从视口或行本身到相邻/首末真实行，跨窗口滚动挂载；内嵌编辑/按钮键位不被接管。", descriptionEn: "From the viewport or row, reach adjacent/first/last actual rows, scrolling/mounting across windows. Embedded editing/button keys remain intact." }],
  notes: ["只有等高项；动态高度、完整 DOM 搜索/打印使用普通集合或 ScrollArea。", "聚焦行即使离屏也保留挂载；真实移除后焦点回到视口，可继续导航。aria-posinset/setsize 表达完整集合位置。", "示例行高 48px 是消费示例选择，视口容纳四项；修改入口是示例 rowSize 与组件 itemSize/height，未新增库 token。"], notesEn: ["Equal-height items only. Use ordinary collections or ScrollArea for dynamic height, complete DOM search, or printing.","Focused rows remain mounted offscreen; actual removal returns focus to the viewport so navigation can continue. aria-posinset/setsize identify positions in the complete collection.","The example's 48px row height is a consumer choice with four visible rows. Adjust example rowSize or component itemSize/height; no library token was added."],
  decisions: "VirtualList 不代表选择、加载或业务结果。稳定 key、等高项和可达窗口是当前契约；overscan=2 是渲染预算预设。", decisionsEn: "VirtualList expresses no selection, loading, or business result. Stable keys, equal-height items, and a reachable window are its current contract; overscan=2 is a rendering-budget preset.",
  design: { methods: ["随境取度", "进退相承", "名实相符"], whenToUse: ["明确等高与稳定身份的长集合"], avoid: ["可变高内容、需要全量 DOM 的内容、业务表格"], composition: ["视口 + 总高空间 + 当前窗口/保留焦点项"], stateOwner: { library: ["窗口、真实位置、焦点连续性"], application: ["集合、稳定 key、等高 extent、项内容"] }, customization: ["itemSize / height / overscan 与公开内容出口"] }, designEn: {"whenToUse":["Long collections with explicit equal heights and stable identities."],"avoid":["Variable heights, content requiring full DOM, or business tables."],"composition":["Viewport + total-height space + current window/retained focused item."],"stateOwner":{"library":["Windowing, actual positions, and focus continuity."],"application":["Collections, stable keys, equal extents, and item content."]},"customization":["itemSize / height / overscan and public content composition."]},
} satisfies ComponentMeta;
