import type { ComponentMeta } from "@/lib/types";
export default {
  title: "空与未知 Empty", titleEn: "Empty", description: "区分零结果、未知与不适用。", descriptionEn: "Distinguish zero results, unknown and not applicable.",
  category: "数据展示", layer: "pattern", source: "local", exports: ["Empty", "EmptyTitle", "EmptyDescription", "EmptyActions"],
  decisions: "调用方提供状态、名称和可执行入口；没有内容不自动建立卡片边界。", decisionsEn: "The caller supplies state, names and real actions; missing content does not automatically require a card boundary.",
  design: { methods: ["名实相符", "相成相制"], whenToUse: ["缺少内容时需要表达零、未知或不适用与可执行入口。"], avoid: ["等待中的内容使用适用的加载状态；刷新时保留已有内容。"], stateOwner: { library: ["名称、说明与动作的关系结构。"], application: ["状态事实、原因、错误恢复与入口可用性。"] }, responsive: ["名称与恢复动作完整换行。"] }, designEn: {"whenToUse":["Missing content needs truthful zero, unknown, or not-applicable facts and actionable entries."],"avoid":["Use an appropriate waiting state for pending content; retain existing content during refresh."],"stateOwner":{"library":["Relationship structure for names, descriptions, and actions."],"application":["State facts, reasons, error recovery, and available entries."]},"responsive":["Names and recovery actions wrap fully."]},
  keywords: ["empty state", "no data", "blank", "空状态", "暂无数据", "无内容", "未知"],
  api: [
    { name: "Empty", description: "div，状态必填。", descriptionEn: "A div with required state.", props: [{ name: "state", type: '"empty" | "unknown" | "not-applicable"', description: "零结果、结果未知或任务不适用。", descriptionEn: "Zero results, unknown results, or a task that does not apply." }, { name: "children / render / ref / native props", type: "useRender.ComponentProps<div>", description: "应用提供内容；不会自动成为 alert。", descriptionEn: "The caller supplies content; the component is not automatically an alert." }] },
    { name: "EmptyTitle", description: "复用 Heading，默认 h2。", descriptionEn: "A Heading composition, defaulting to h2.", props: [{ name: "level / step / render / ref / Heading props", type: "HeadingProps", description: "标题层级由文档关系决定。", descriptionEn: "Document relationships determine heading level." }] },
    { name: "EmptyDescription / EmptyActions", description: "p 说明与 div 动作关系。", descriptionEn: "p explanation and div action grouping.", props: [{ name: "children / render / ref / native props", type: "useRender.ComponentProps<p | div>", description: "动作复用公共组件与合法原生语义。", descriptionEn: "Compose public controls with valid native semantics." }] },
  ], notes: ["保留刷新前的有效内容，不把尚未加载或不适用标成 0 条。"], notesEn: ["Retain valid content while refreshing; do not label unloaded or inapplicable results as zero."],
} satisfies ComponentMeta;
