import { Button } from "@qingye/ui/components/button";
import { Checkbox } from "@qingye/ui/components/checkbox";
import { Label } from "@qingye/ui/components/label";
import { Progress } from "@qingye/ui/components/progress";
import { Inline, Stack } from "@qingye/ui/components/layout";
import { useId, useState } from "react";
import { A, H2, P, PageHeader } from "@/components/prose";
import { useDocsLocale } from "@/lib/docs-locale";
export default function AccessibilityPage() {
  const en = useDocsLocale() === "en";
  const base = useId(); const [checked,setChecked] = useState<Set<number>>(new Set());
  const items = en ? ["Keyboard reaches the task's controls in reading order; focus remains visible inside their boundaries.", "Controls have accurate names and states; field labels and errors are associated with the input.", "Normal text, including supporting text, reaches 4.5:1 contrast. Check large text and necessary non-text content under their applicable requirements, in both themes.", "Closing an overlay restores useful focus. Failure and cancellation preserve the work needed to recover."] : ["键盘按阅读顺序到达任务控件，焦点在控件边界内清晰可见。", "控件名称与状态准确，字段标签和错误与输入关联。", "普通文字含辅助文字达到 4.5:1 对比度；大文本及必要非文本按适用要求检查，浅深色均核对。", "浮层关闭后归还有效焦点，失败与取消保留恢复所需工作。"];
  return <article><PageHeader title={en ? "Accessibility" : "无障碍"} /><H2 id="ownership">{en ? "Shared responsibility" : "共同责任"}</H2><P>{en ? "Public primitives provide interaction mechanics. The application provides truthful names, content, document structure, and state. Verify the actual composition with a keyboard and assistive technology." : "公共原语提供交互机制；应用提供真实名称、内容、页面结构与状态。实际组合需要用键盘和辅助技术验证。"} <A href="/docs/components">{en ? "Component contracts" : "组件契约"}</A></P><H2 id="targets">{en ? "Contrast and targets" : "对比度与命中区"}</H2><P>{en ? "A token name does not prove contrast. Test rendered foregrounds against their actual backgrounds. The library's coarse-pointer target is 44px; this is not a universal WCAG 2.2 AA minimum. WCAG 2.5.8 has a 24×24px baseline with defined exceptions." : "令牌名不能证明对比度，需检查实际前景与背景。库的粗指针目标为 44px，不是 WCAG 2.2 AA 对所有元素的统一最小值；2.5.8 基础要求为 24×24px，并有适用例外。"}</P><H2 id="checklist">{en ? "Record your checks" : "记录你的检查"}</H2><P>{en ? "These marks record your own checks for this visit; they are not an automatic conformance result." : "勾选记录本次访问中你完成的检查，不是自动合规结论。"}</P><Stack gap="fields"><Inline><Progress aria-label={en ? "Recorded checks" : "已记录检查"} value={checked.size} max={items.length} className="w-32" /><output aria-live="polite">{checked.size} / {items.length}</output><Button variant="quiet" disabled={checked.size === 0} onClick={() => setChecked(new Set())}>{en ? "Clear" : "清空"}</Button></Inline>{items.map((item,index) => <Inline align="start" key={index}><Checkbox id={`${base}-${index}`} checked={checked.has(index)} onCheckedChange={next => setChecked(prev => { const value = new Set(prev); next ? value.add(index) : value.delete(index); return value; })} /><Label className="flex-1" htmlFor={`${base}-${index}`}>{item}</Label></Inline>)}</Stack><H2 id="evidence">{en ? "Verification limits" : "验证边界"}</H2><P>{en ? "Static checks and viewport screenshots do not replace keyboard, screen-reader, or real-device evidence. Keep unrun checks distinct from passed checks." : "静态检查与视口截图不能替代键盘、读屏或真实设备证据，未运行与通过分别记录。"}</P></article>;
}
