import { buttonVariants } from "@qingye/ui/components/button";
import { A, Code, H2, Ol, P, PageHeader } from "@/components/prose";
import { CodeBlock } from "@/components/code-block";
import { CopyCodeButton } from "@/components/copy-code-button";
import { SITE } from "@/lib/site";
import { designEntryFor } from "@/lib/design-entry";
import { useDocsLocale } from "@/lib/docs-locale";
export default function AIPage() {
  const locale = useDocsLocale(); const en = locale === "en"; const entry = designEntryFor(locale); const guideFile = en ? "design.en.md" : "design.md";
  return <article><PageHeader title={en ? "Bring methods and facts to AI" : "把方法与事实交给 AI"} /><div className="qy-task-actions"><a className={buttonVariants()} download href={`/${guideFile}`}>{en ? "Download guide" : "下载指南"}</a><CopyCodeButton value={entry.guide} label={en ? "Copy design guide" : "复制设计指南"} /><a className={buttonVariants({ variant: "quiet" })} download href={en ? "/ai/SKILL.en.md" : "/ai/SKILL.md"}>Skill</a></div>
    <H2 id="project-rules">{en ? "Make project guidance persistent" : "让项目引用持续生效"}</H2><Ol><li><A href="/docs/installation">{en ? "Install and configure the library" : "安装并配置组件库"}</A>{en ? ", then check the actual installed version." : "，核对实际安装版本。"}</li><li>{en ? "Merge the snippets below into the project's existing AGENTS.md and design.md. Preserve its existing rules and design constraints." : "将下方片段合并到项目已有 AGENTS.md 与 design.md，保留既有规则与设计约束。"}</li><li>{en ? "Have the AI tool load project guidance according to its own rules. At the start of a UI task, read the local guide, current API, and project entry points." : "让 AI 工具按自身规则加载项目说明；界面任务开始时读取本地指南、当前 API 与项目入口。"}</li></Ol><CodeBlock code={entry.agents} lang="text" title="AGENTS.md" /><CodeBlock code={entry.design} lang="text" title="design.md" /><P>{en ? `The references point to node_modules/@qingye/ui/${guideFile}. If your installed package lacks the guide, download it to docs/qingye-design.md and update the references. Downloading alone does not configure a tool or authorize changes in another project.` : "片段引用 node_modules/@qingye/ui/design.md；安装版缺少指南时，下载到 docs/qingye-design.md 并更新引用。下载文件不会自动配置工具，也不授予修改其他项目的权限。"}</P>
    <H2 id="start">{en ? "Start with the installed version" : "从实际安装版本开始"}</H2><P>{en ? `The website uses workspace v${SITE.version}, which may precede a release. The installed exports and declarations define the API you can use.` : `本站工作区 v${SITE.version} 可能先于 Release；实际安装的导出与声明决定可用 API。`}</P><CodeBlock code={'node -p "require(\'@qingye/ui/package.json\').version"'} lang="shell" /><P><a className="focus-ring rounded-item underline" href="/catalog.json">catalog.json</a>{en ? " records exports, declarations, examples, and verification limits. Inspect unresolved signatures in local declarations before using them." : " 记录导出、声明、示例与验证边界，无法解析的签名在使用前核对本地声明。"}</P>
    <H2 id="task">{en ? "A task entry" : "任务入口"}</H2><CodeBlock code={entry.task} lang="text" /><P>{en ? "State the application-owned objects, drafts, scope, permissions, versions, and async outcomes. Report success only after the corresponding result is confirmed." : "写明应用管理的对象、草稿、范围、权限、版本与异步结果，对应事实确认后再显示成功。"}</P>
    <H2 id="resources">{en ? "Read versioned resources as needed" : "按需读取版本资料"}</H2><P><a className="focus-ring rounded-item underline" href={`/ai/v${SITE.version}/${en ? "en/" : ""}llms.txt`}>v{SITE.version} · llms.txt</a> · <A href="/docs/components">{en ? "Current components" : "当前组件"}</A> · <A href="/examples">{en ? "Simple compositions" : "简单组合"}</A></P>
    <H2 id="evidence">{en ? "Record what happened" : "记录实际发生的事"}</H2><P>{en ? "Keep source, rendered styles and interaction, assistive technology, and human visual observations distinct. Unknown results need verification; checks not run cannot be recorded as passed." : "源码、渲染样式与交互、辅助技术及人工视觉观察分别记录。未知结果先核实，未运行不能记作通过。"}</P>
  </article>;
}
