import { buttonVariants } from "@qingye_lab/ui/components/button";
import { linkClassName } from "@qingye_lab/ui/components/link";
import { A, H2, Ol, P, PageHeader, Ul } from "@/components/prose";
import { CodeBlock } from "@/components/code-block";
import { CopyCodeButton } from "@/components/copy-code-button";
import { SITE } from "@/lib/site";
import { designEntryFor } from "@/lib/design-entry";
import { useDocsLocale } from "@/lib/docs-locale";
export default function AIPage() {
  const locale = useDocsLocale(); const en = locale === "en"; const entry = designEntryFor(locale); const guideFile = en ? "design.en.md" : "design.md";
  return <article><PageHeader title={en ? "Using AI" : "AI 使用"} description={en ? "Give AI tools the design guide, the installed API and your project's entry points." : "把设计指南、已安装的 API 与项目入口交给 AI 工具。"}><div className="flex flex-wrap items-center gap-(--qy-action-gap) pt-[calc(var(--qy-space-module)-var(--qy-field-gap))]"><a className={buttonVariants()} download href={`/${guideFile}`}>{en ? "Download guide" : "下载指南"}</a><CopyCodeButton value={entry.guide} label={en ? "Copy design guide" : "复制设计指南"} /><a className={buttonVariants({ variant: "quiet" })} download href={en ? "/ai/SKILL.en.md" : "/ai/SKILL.md"}>Skill</a></div></PageHeader>
    <H2 id="project-rules">{en ? "Add to a project" : "接入项目"}</H2><Ol><li><A href="/docs/installation">{en ? "Install the library" : "安装组件库"}</A>{en ? " and check the installed version (see Version below)." : "，并核对实际安装的版本（见下文「版本」）。"}</li><li>{en ? "Merge the two snippets below into the project's existing AGENTS.md and design.md, keeping its rules and design constraints." : "把下面两段合并进项目已有的 AGENTS.md 与 design.md，保留原有的规则与设计约束。"}</li><li>{en ? "Let the AI tool load AGENTS.md by its own rules. At the start of a UI task it then reads the local guide, the current API and the project entry points." : "让 AI 工具按自身规则加载 AGENTS.md；开始界面任务时，它会读取本地指南、当前 API 与项目入口。"}</li></Ol><CodeBlock code={entry.agents} lang="text" title="AGENTS.md" /><CodeBlock code={entry.design} lang="text" title="design.md" /><P>{en ? `The snippets point to node_modules/@qingye_lab/ui/${guideFile}. If the installed package lacks it, save the downloaded guide as docs/qingye-design.md and update the references. Downloading alone configures no tool.` : "片段指向 node_modules/@qingye_lab/ui/design.md。安装包里没有这份文件时，把下载的指南存为 docs/qingye-design.md，并改写引用。下载本身不会配置任何工具。"}</P>
    <H2 id="start">{en ? "Version" : "版本"}</H2><P>{en ? `This site documents workspace v${SITE.version}, which may be ahead of a release. The exports and declarations you installed decide which API exists. Check the installed version:` : `本站记录的是工作区 v${SITE.version}，可能早于正式发布；可用的 API 以你安装的导出与类型声明为准。查看已安装的版本：`}</P><CodeBlock code={'node -p "require(\'@qingye_lab/ui/package.json\').version"'} lang="shell" /><P><a className={linkClassName} href="/catalog.json">catalog.json</a>{en ? " lists exports, declarations, examples and verification limits. Check any signature it cannot resolve against the local declarations before use." : " 列出导出、声明、示例与验证边界；其中无法解析的签名，使用前对照本地声明核对。"}</P>
    <H2 id="task">{en ? "A task entry" : "任务入口"}</H2><CodeBlock code={entry.task} lang="text" /><P>{en ? "Name the objects, drafts, scope, permissions, versions and async outcomes your application owns. Show success only after the matching result is confirmed." : "写明应用持有的对象、草稿、范围、权限、版本与异步结果；对应结果确认之后，界面才显示成功。"}</P>
    <H2 id="resources">{en ? "Versioned resources" : "版本资料"}</H2><Ul><li><a className={linkClassName} href={`/ai/v${SITE.version}/${en ? "en/" : ""}llms.txt`}>v{SITE.version} · llms.txt</a></li><li><A href="/docs/components">{en ? "Current components" : "当前组件"}</A></li><li><A href="/examples">{en ? "Examples" : "示例"}</A></li></Ul>
    <H2 id="evidence">{en ? "Recording results" : "记录结果"}</H2><P>{en ? "Record source, rendered styles and interaction, assistive technology and human visual checks separately. A check that was not run is unverified, not passed." : "源码、渲染样式与交互、辅助技术与人工目视分别记录。没有运行的检查记为未验证，不记为通过。"}</P>
  </article>;
}
