import type { ComponentMeta } from "@/lib/types";

export default {
  title: "建议输入 Autocomplete", titleEn: "Autocomplete",
  description: "编辑自由文本，候选作为可接受的建议。", descriptionEn: "Edit free text with optional suggestions.",
  category: "表单", source: "local", layer: "pattern", exports: ["Autocomplete", "AutocompleteInput", "AutocompleteTrigger", "AutocompleteClear", "AutocompletePopup", "AutocompleteList", "AutocompleteItem", "AutocompleteEmpty", "AutocompletePrimitive"], keywords: ["autocomplete", "suggestion", "自由文本", "建议"],
  decisions: "输入文字本身就是值。移动候选高亮不改变文本；确认建议才请求替换，文本无需匹配候选也可提交。",
  decisionsEn: "The text itself is the value. Highlighting does not change it; accepting a suggestion requests replacement. Text can submit without matching a suggestion.",
  api: [{ name: "Autocomplete", description: "Base UI 文本建议上下文，固定 list 模式。", descriptionEn: "A Base UI text-suggestion context fixed to list mode.", props: [
    { name: "value / defaultValue / onValueChange", type: "string / string / (value, details) => void", description: "受控或非受控自由文本；details.cancel() 可拒绝编辑或接受建议请求。", descriptionEn: "Controlled or uncontrolled free text. details.cancel() can reject edits or suggestion requests." },
    { name: "items / itemToStringValue / filter", type: "readonly Value[] / Base UI public props", description: "提供平坦建议数组、建议文字与过滤规则；对象建议显式定义文本。分组等高级组合可用 AutocompletePrimitive。", descriptionEn: "Provide flat suggestions, their text, and filtering. Define text for object suggestions. Use AutocompletePrimitive for grouped advanced compositions." },
    { name: "name / form / required / disabled / readOnly", type: "Base UI Root props", description: "实际 Input 与 Field 注册一次，FormData 提交自由文本；只读提交、禁用排除。", descriptionEn: "The actual input registers Field once and submits free text. Read-only submits; disabled is excluded." },
    { name: "open / defaultOpen / onOpenChange", type: "Base UI open props", description: "展开可控；文本、动作与建议项共用一套几何，跟随密度轴。", descriptionEn: "Opening is controllable. Input, actions, and suggestions share one geometry that follows the density axis." },
  ] }, { name: "AutocompleteInput / AutocompleteTrigger / AutocompleteClear", description: "共享 Input/Button 的真实出口，透传 ref/render/ARIA/events；清除请求空文本。", descriptionEn: "Real Input/Button outlets forwarding refs, render, ARIA, and events. Clear requests empty text." }, { name: "AutocompletePopup", description: "公开候选 Portal/Positioner/Popup；container/positionerProps 透传并消费共享浮层层级。", descriptionEn: "Public candidate Portal/Positioner/Popup forwarding container and positionerProps with shared layer order." }, { name: "AutocompleteList / AutocompleteItem / AutocompleteEmpty", description: "建议集合、文字建议与调用方真实空内容。", descriptionEn: "Suggestion list, text suggestions, and caller-provided real empty content." }, { name: "AutocompletePrimitive", description: "安装版 Base UI Autocomplete 命名空间。", descriptionEn: "The installed Base UI Autocomplete namespace." }],
  keyboard: [{ keys: "ArrowDown / ArrowUp", description: "高亮建议，输入文字与 FormData 保持当前文本。", descriptionEn: "Highlight suggestions while text and FormData retain the current value." }, { keys: "Enter", description: "请求接受高亮建议的文字。", descriptionEn: "Request the highlighted suggestion text." }, { keys: "Escape / Tab", description: "退出列表，输入仍可编辑与提交。", descriptionEn: "Leave the list; text remains editable and submittable." }],
  notes: ["需要只能确认候选中的一个值时用 Combobox。", "空集合不代表错误或服务失败；空提示由调用方根据真实情况提供。", "caller 定位 style 最后合并；颜色、圆角、高亮与焦点读取现有主题角色。"],
  notesEn: ["Use Combobox when a value must be confirmed from candidates.", "An empty set does not imply an error or service failure. Supply empty content from real facts.", "Caller positioning style merges last; colors, corners, highlights, and focus use existing theme roles."],
  design: { methods: ["名实相符", "相成相制", "进退相承"], composition: ["Field + FieldLabel + Autocomplete / Input / actions / Popup / List / Item"], stateOwner: { library: ["建议高亮、焦点、非受控文本"], application: ["受控文本、建议数据、错误与提交结果"] }, responsive: ["一套几何，跟随密度轴，紧凑不缩小文字；浮层受可用空间约束"], customization: ["公开 parts/原语、render/ref/ARIA/events 与共享浮层"] }, designEn: {"composition":["Field + FieldLabel + Autocomplete / Input / actions / Popup / List / Item"],"stateOwner":{"library":["Suggestion highlighting, focus, and uncontrolled text."],"application":["Controlled text, suggestion data, errors, and submission outcomes."]},"responsive":["One geometry following the density axis; compact tightens the container, never the text; the popup is constrained by available space."],"customization":["Public parts/primitives, render/refs/ARIA/events, and shared floating layers."]},
} satisfies ComponentMeta;
