import type { ComponentMeta } from "@/lib/types";
export default {
  title: "文件输入 FileUpload", titleEn: "FileUpload",
  description: "选择或拖入本地文件，保留已接受集合与真实拒绝原因。", descriptionEn: "Choose or drop local files, retaining accepted files and real rejection reasons.",
  category: "表单", source: "local", layer: "pattern", exports: ["FileUpload", "FileUploadPrimitive"], keywords: ["files", "文件", "drop", "upload"],
  decisions: "组件只管理本地文件选择。上传状态、进度分母、失败、结果未知与恢复由应用提供；它不发请求、不制造进度、不从 Promise 推断结果。",
  decisionsEn: "The component manages local selection only. The application supplies upload states, progress denominators, failure, unknown results, and recovery. It sends no requests, invents no progress, and infers no result from a Promise.",
  api: [{ name: "FileUpload", description: "原生 file Input、拖放、已接受列表与真实规则验证的组合。", descriptionEn: "A native file input composed with dropping, accepted files, and real rule validation.", props: [
    { name: "value / defaultValue / onValueChange", type: "readonly File[] / readonly File[] / (files, details) => void", default: "defaultValue: []", description: "受控或非受控接受集合，保留 File 引用。details 含 select/drop/remove、added/removed/event/cancel()；受控拒绝或取消不改变提交集合。", descriptionEn: "Controlled or uncontrolled accepted files, retaining File references. details includes select/drop/remove, added, removed, event, and cancel(). Refusal or cancellation preserves submitted files." },
    { name: "accept / maxSize / maxFiles", type: "string / number / number", description: "扩展名/MIME规则、每文件字节数、集合数量。大小与数量为非负安全整数，省略不限制；按 type/size/count 的实际首个失败理由拒绝，已知外部集合不静默纠正。", descriptionEn: "Extension/MIME rules, bytes per file, and collection count. Size and count are nonnegative safe integers; omitted means unlimited. Reject with the first actual type/size/count failure; external sets are not silently repaired." },
    { name: "multiple", type: "boolean", default: "true", description: "默认是集合选择；false 的集合容量最多1，已有文件须先移除才能加入另一个，不隐式替换。", descriptionEn: "Defaults to collection selection. false limits capacity to one; remove an existing file before adding another, with no implicit replacement." },
    { name: "onReject", type: "(rejections: {file, reason}[], event) => void", description: "真实 type/size/count 拒绝；拒绝项可关闭提示，但不冒充已接受文件。", descriptionEn: "Actual type/size/count rejections. Dismissing feedback does not make rejected files accepted." },
    { name: "name / form", type: "string", description: "chooser 不带最终 name；Field 可提供名称，公开 formdata 事件 append 已接受 File，不覆盖同名其它字段。显式 form 支持外部表单。", descriptionEn: "The chooser has no final name. Field may supply it; the public formdata event appends accepted Files without replacing other same-name fields. form supports external forms." },
    { name: "disabled / readOnly", type: "boolean", default: "false", description: "阻止选择、拖放和移除；Field/原生 fieldset 禁用同样约束。只读文件继续提交，禁用排除。原生 reset 未取消时非受控恢复初始 defaultValue，受控值保留。", descriptionEn: "Block selecting, dropping, and removing, including Field/native fieldset disabled. Read-only submits; disabled is excluded. Uncanceled native reset restores initial uncontrolled defaultValue and retains controlled values." },
    { name: "getStatus", type: "(file) => {state, label, progress?} | undefined", description: "调用方真实 waiting/in-progress/failed/unknown/success 与可见 label。只有 in-progress 可提供 {value, min?, max}；max 是调用方已知分母，null 为不定进度。", descriptionEn: "Caller-provided waiting/in-progress/failed/unknown/success and a visible label. Only in-progress accepts {value,min?,max}; max is a known denominator and null is indeterminate." },
    { name: "renderFileActions", type: "(file, status) => ReactNode", description: "应用的实际恢复/核对入口，组件不自动执行；本地移除不表示取消上传或删除服务端对象。", descriptionEn: "Real application recovery/check actions, never executed automatically. Local removal does not imply canceling an upload or deleting a server object." },
    { name: "inputProps / render / ref / ARIA / events", type: "current Input props / div composition", description: "选择动作与编辑边界共用一套几何（跟随密度轴）；Input 出口支持 render/ref/events。required 不暴露，chooser 会清空；集合必填由应用按当前 value 校验并用 FieldError 表达。", descriptionEn: "The chooser shares one geometry with the editing boundary (density axis). Input supports render, refs, and events. required is not exposed because the chooser clears; validate the current set in the application with FieldError." },
  ] }, { name: "FileUploadPrimitive", description: "所用安装版 Input 原语命名空间。", descriptionEn: "The installed Input primitive namespace." }],
  keyboard: [{ keys: "Tab / Enter / Space", description: "到真实原生文件入口并选择；只读阻止修改。", descriptionEn: "Reach and activate the real native file chooser; read-only blocks changes." }, { keys: "Tab / Enter", description: "移除已接受本地文件或关闭拒绝提示；应用恢复入口遵守其自身事实。", descriptionEn: "Remove accepted local files or dismiss rejections; recovery actions follow application facts." }],
  notes: ["对象身份决定集合成员；不凭同名/大小猜文件内容相同。移除后可重新选择同一文件；聚焦行移除回相邻动作或 chooser，受控拒绝不夺焦点。", "Field 保留 Label/error/disabled 连接；实际 chooser 的 name/value/required 隔离，避免提交草稿或恒 invalid。", "需要支持 formdata 的浏览器；jsdom 事件桥接不等于已验证原生 FormData 构造行为。", "规则值是应用约束，列表/拖放布局是选择，样式读现有角色，无额外数值 token。", "选择入口只显示操作名称，原生 chooser 清空用于重选；已接受文件事实以独立集合呈现。装饰 span 不创建第二交互入口。"],
  notesEn: ["Object identity determines membership; equal names/sizes do not imply equal content. Removed files can be reselected. Removing a focused row returns to a neighboring action or chooser; controlled refusal preserves focus.", "Field retains label/error/disabled links. The actual chooser isolates name, value, and required to avoid draft submission or permanent invalidity.", "Requires browser formdata support. A jsdom event bridge does not verify native FormData construction.", "Rules are application constraints; list/drop layout is a choice. Styles use existing roles without new numeric tokens.", "The chooser displays its action name and clears for reselection. The separate list expresses accepted files. Its decorative span creates no second interaction entry."],
  design: { methods: ["名实相符", "进退相承", "相成相制"], composition: ["Field + FieldLabel + FileUpload + 实际规则说明/FieldError"], stateOwner: { library: ["选择、拖放、非受控本地集合、真实拒绝"], application: ["受控集合、接受规则、上传状态/进度、恢复与结果"] }, responsive: ["原生 Input/Button 一套几何，跟随密度轴，紧凑不缩小文字，文件名按真实容量换行"], customization: ["Input/根 render/ref/ARIA/events、getStatus、恢复入口及现有主题"] }, designEn: {"composition":["Field + FieldLabel + FileUpload + actual rule explanation/FieldError"],"stateOwner":{"library":["Selection, drop, uncontrolled local collection, and actual rejection."],"application":["Controlled collection, acceptance rules, upload state/progress, recovery, and outcomes."]},"responsive":["Native Input/Button use five matching text profiles; filenames wrap within actual capacity."],"customization":["Input/root render/refs/ARIA/events, getStatus, recovery entries, and existing theme."]},
} satisfies ComponentMeta;
